### ISSUE TITLE
Horizon not enabled by default in Docker deployments

### ISSUE THREAD

**Issue by johackim** [pixelfed/pixelfed#1026]
Hello, 

Thanks for this project !

I launched my pixelfed instance but previews are not displayed.

![](https://i.imgur.com/Qaandbf.png)

**Comment by trwnh** [comment]
Did you upload a video or a GIF? The thumbnail generator currently only works on static image types.

**Comment by johackim** [comment]
Hello @trwnh,

No just png or jpeg images

**Comment by trwnh** [comment]
Can you post a link to your profile?

**Comment by johackim** [comment]
@trwnh 

https://instagram.ston3o.me/ston3o

**Comment by trwnh** [comment]
Did you upload via the Classic or the Experimental uploader?

**Comment by ston3o** [comment]
I tested both

**Comment by johackim** [comment]
@trwnh I tested both

**Comment by trwnh** [comment]
Were you uploading really big pictures?

**Comment by johackim** [comment]
@trwnh I tested images ranging from 330K to 2M

**Comment by trwnh** [comment]
Hmm. The only thing I noticed while trying to load your image posts was that some of them were not loading instantly, so that's why I suspected size had something to do with it.

More interestingly, I have just managed to reproduce this on pixelfed.social by uploading a 13583 x 5417 image, which generated no thumbnail. So what was the resolution of the photos you were uploading? Data size is not really important, I think it has to do with the dimensions.

**Comment by johackim** [comment]
@trwnh  I uploaded images from 615x615 pixels to 4952x3446

**Comment by trwnh** [comment]
OK, the big image I uploaded just had its thumbnail generated after some time. So it looks like your instance is not running the thumbnail generator task in the background, for some reason.

**Comment by johackim** [comment]
Oh thanks @trwnh , in fact, horizon it's not enable by default with docker environment, when I launch `php artisan horizon` command, it's works ! Thanks @trwnh !

**Comment by trwnh** [comment]
Glad to hear you figured out the cause! Reopening this issue to track changes to Docker deployment scripts.

**Comment by dansup** [comment]
Fixed in latest commits!
