### ISSUE TITLE
Mirror to Instagram

### ISSUE THREAD

**Issue by 360fun** [pixelfed/pixelfed#1080]
Hi! I found this API:
https://github.com/mgp25/Instagram-API

Would be great to integrate it so people could start immediately to use PixelFed and attract people from Instagram at the same time! ;)

**Comment by trwnh** [comment]
This is something that is best handled by a third-party app.

**Comment by dansup** [comment]
@360fun Instagram has disabled the APIs required for this, and using private APIs would violate the Terms of Use of their platform which could get your account suspended.

https://www.instagram.com/developer/

**Comment by 360fun** [comment]
good to know, thanks! ;)

> @360fun Instagram has disabled the APIs required for this, and using private APIs would violate the Terms of Use of their platform which could get your account suspended.
> 
> https://www.instagram.com/developer/

**Comment by kojid0** [comment]
Coming from #2309 with an alternative idea without the need to rely on API.

What about a simple "Enable Cross-Posting" option in settings of the upcoming app to enable that pixelfed asks to share the uploaded content with another app, e.g. instagram? 
There is no need to implement some api into pixelfeed, it can purely rely on the "share" functionality of Android/iOS (when your app is ready).

So if the user has enabled it in settings, pixelfed could
1. ask user if he wants to share the content to another app as well
2. if yes, open a page in pixelfed to modify the picture again before sharing (e.g. to let user decide to auto-blur the photo and place something like "👉🏼new post on pixelfed.social" with a clickable direct link in order to "appetite" friends who want to know what's going on)
3. open the Android/iOS share menu. From this point, it's up to the user what he does with it (e.g. share with instagram, share with email app, share via bluetooth, save to gallery,...)

What do you think about it? Maybe this issue can be reopened or tagged for later discussions/decisions when the app is ready?

**Comment by 360fun** [comment]
> Coming from #2309 with an alternative idea without the need to rely on API.
> 
> What about a simple "Enable Cross-Posting" option in settings of the upcoming app to enable that pixelfed asks to share the uploaded content with another app, e.g. instagram?
> There is no need to implement some api into pixelfeed, it can purely rely on the "share" functionality of Android/iOS (when your app is ready).
> 
> So if the user has enabled it in settings, pixelfed could
> 
> 1. ask user if he wants to share the content to another app as well
> 2. if yes, open a page in pixelfed to modify the picture again before sharing (e.g. to let user decide to auto-blur the photo and place something like "👉🏼new post on pixelfed.social" with a clickable direct link in order to "appetite" friends who want to know what's going on)
> 3. open the Android/iOS share menu. From this point, it's up to the user what he does with it (e.g. share with instagram, share with email app, share via bluetooth, save to gallery,...)
> 
> What do you think about it? Maybe this issue can be reopened or tagged for later discussions/decisions when the app is ready?

this can be an interesting solution, especially the "👉🏼new post on pixelfed.social": this is the kind of techniques that could help spread Fediverse around (using common socials)

**Comment by Megver83** [comment]
Just fyi, there's another unofficial API here:

https://github.com/ping/instagram_private_api

> @360fun Instagram has disabled the APIs required for this, and using private APIs would violate the Terms of Use of their platform which could get your account suspended.

so then, if adding this option, a warning talking about the potential blocking can be put there too, plus, we should test it before assuring anything

**Comment by kojid0** [comment]
I wouldn't like pixelfed to implement something that supports/promotes a proprietary software. Also, F-droid might mark pixelfed with a warning if the app eventually gets published there and it's not worth it. 
I think the solution I posted is a compromise. It is probably not hard to implement and not a big workaround/time intensive process for the user.

**Comment by 360fun** [comment]
What about an extension/plugin system (if it's not already implemented) very easy to use and with "the store" already integrated (like WordPress)? So people are 2 clicks away from several options and can choose the one fitting their needs.

**Comment by kamazeuci** [comment]
I think this should be a big priority... otherwise... is there a place where we can find strategies for migrating people from dystopian platforms to ethical libre ones? We should set steps.

**Comment by CaptainStack** [comment]
I would like a way to do this and it would help me switch more fully to Pixelfed.

**Comment by adrian-amaglio** [comment]
Is there some news about this "auto cross-posting" feature?
It would be a very convenient transition help for curious instagramers.

**Comment by timolaine** [comment]
I would be really interested in this feature. I have an Instagram account but would like to start using Pixelfed in order to be less dependent on Meta.
