### ISSUE TITLE
Suggestion: look & feel GUI

### ISSUE THREAD

**Issue by Vertux** [pixelfed/pixelfed#1099]
Just for inspiration, this is a screenshot from [500px.com](https://500px.com), I really like the slim, elegant and informative GUI - for a FOSS project it would be nice not to recycle too much look & feel of Instagram/Facebook, Pixelfed sould have its own "personality"

![Bildschirmfoto 2019-03-30 um 14 26 09](https://user-images.githubusercontent.com/10457918/55278056-aafb8e80-5307-11e9-983c-87c1b4ad3dce.png)

**Comment by mkljczk** [comment]
I believe that cloning Instagram UI is a good starting point, as dansup makes lots of improvements to it. With these tons of enhancements, PixelFed gains its own ‘personality’

**Comment by hellcp** [comment]
Alternative frontends were discussed but no decision was really made on support of that, especially since for more advanced 500px/flickr frontends we would need to collect excessive amounts of exif data.

**Comment by trwnh** [comment]
Closing this issue as not actionable. If there is a specific request or suggestion, please feel free to file a new issue for that!

**Comment by Vertux** [comment]
When I personally heard of Pixelfed the first time, I thought it is gonna be a great plattform for photo enthusiasts (the name already creates this impression), but at the moment it seems that the development is very concentrated on copying the Instagram look & feel. Well, I think you massivly underestimate the potential user base of photo enthusiasts, who may be a little disappointed at the moment, because they are used to handle images more serious - not only as "fun postings". These people, normally expect a much more photo oriented user interface e.g the possibility to select and display a licence, at least basic EXIF information, GPS data, categories etc. 
In my humble opinion it would be a little sad if Pixelfed would "just" become a dezentralized open source copy of Instagram. I just wanted to show you another user perspective.

**Comment by trwnh** [comment]
@Vertux Which specific features are you interested in seeing as a photo enthusiast? Keep in mind the things you listed already exist:

- License: #13 
- EXIF: #499
- Categories: #270 

Again, please feel free to file more specific feature requests if you have any more.

As far as the "purpose" of Pixelfed, it is not necessarily aimed at only "fun postings" or "serious images", but the exact model / paradigm we are using is "statuses with media attached" rather than "images with captions attached". The focus of the platform is therefore targeted a bit more at publishing updates rather than maintaining libraries.

**Comment by Vertux** [comment]
@trwnh thank you for pointing me to the features, which are already on the feature list. I am sorry, I did no search before I have posted my last comment.

> "statuses with media attached" 

That's a good and very neutral paradigm, I think it do justice to all interest groups.

**Comment by trwnh** [comment]
I don't really think it's possible to have a neutral model. Either the status is the base object, or the image is the base object. In Pixelfed we have chosen the status. There is certainly room for other implementations that choose the image as base. But those implementations would necessarily be more focused on image management than status sharing. Anfora and peerpx are examples of such projects that aim to provide users with a photo gallery shareable over ActivityPub, rather than a social network based on media posts.

Of course, at the UI level this is a bit more flexible. But the underlying focus on publishing updates is still there.

**Comment by Vertux** [comment]
> Anfora and peerpx are examples of such projects that aim to provide users with a photo gallery shareable over ActivityPub

Interesting, I hadn't heard of these projects before.

**Comment by trwnh** [comment]
There is also now experimental Moment UI, which can be enabled by a profile's owner. See https://pixelfed.social/trwnh for a live example, and https://pixelfed.social/p/trwnh/276 for an example post
