### ISSUE TITLE
Hashtags not working

### ISSUE THREAD

**Issue by c3x** [pixelfed/pixelfed#1201]
Hello.
Fresh installation from today.
When I add a caption with #hashtags, than these are not linked. Hashtags in the comments are linked but I got an "page not found", if I follow the link (/discover/tags/cool?src=hash).

![firefox_2019-04-25_16-16-49](https://user-images.githubusercontent.com/8462728/56724776-d726f580-6775-11e9-9fc0-da9131b99bbc.jpg)

**Comment by stanclai** [comment]
idk, if this issue is related to my problem, but I've noticed strange behavior with hashtags too (in versions 0.9 and 0.9.1).

what I do: I write post description with some hashtags, say `#Autumn #Leaves`. this post goes w/o problems. then I make another post with word `#leaves` (not capitalized) as a hashtag. when I press `Publish` button, the post appears as a plain text (w/o linked hashtags), and in Horizon stats I get failed job `App\Jobs\StatusPipeline\StatusEntityLexer` with error `duplicate key value violates unique constraint "hashtags_slug_unique"`.

probably, the right behavior would be interpret hashtags regardless of their capitalization.

what I've found so far.

* the mentioned job calls a function `storeHashtags()` which [calls another function](https://github.com/pixelfed/pixelfed/blob/dev/app/Jobs/StatusPipeline/StatusEntityLexer.php#L95) `Hashtag::firstOrCreate(['name' => $tag, 'slug' => $slug])`.
* in the table `hashtags` (which is the data-set for `Hashtag::firstOrCreate`) there are two fields with constraint `UNIQUE`: `name` and `slug`. at this point it's quite logical, I agree.
* when `StatusEntityLexer` requests the first record with given pair [name, slug], and the name part is differs (in case-sensitive sense), naturally, we receive nothing.
* and then, since we didn't get existing record, we try to create one. and here we catch an error, 'cos `slug` *must be unique*.

as I don't know Laravel framework and don't write in PHP, I can't, unfortunately, propose ready-to-implement solution. :( but in general I see at least three ways.

1. if constraint for `slug` will be removed, it will be possible to have as much different `name` field values, as it could be generated by all case-insensitive combinations. but in such case it will be possible to have totally unrelated names linked to same slug (in consequence of some less probable error in code).
2. since names should be considered as case-insensitive, probably it would be possible  to remove the field `name` entirely and leave only `slug`. but in such case we lose information about capitalization in tags, which may be important for some users.
3. break table `hashtags` into 2 tables with relation many-to-one: one table with names (“many” part) and another table with slugs (“one” part). so we can preserve names case-sensitivity and uniqueness both for names and slugs. possibility to have unrelated name/slug names is present here too, but it can be corrected more easy in such case.

**Comment by c3x** [comment]
> table hashtags

My hashtags table are empty.
The hashtags are only visible in the table "statuses". The table "status_hashtags" is also empty.

![firefox_2019-04-26_16-23-34](https://user-images.githubusercontent.com/8462728/56797799-b4f9aa00-683f-11e9-963b-6b20cc1f0d25.jpg)

**Comment by dansup** [comment]
@c3x What database are you using, postgres?

**Comment by c3x** [comment]
@dansup No, I use MariaDB [10.3.14-MariaDB-1:10.3.14+maria~stretch-log] on Debian 9 with PHP 7.2 [PHP 7.2.17-1+0~20190412071344.20+stretch~1.gbp23a36d (cli) (built: Apr 12 2019 07:13:45) ( NTS )]

**Comment by c3x** [comment]
@dansup Just did an "composer update" and hashtags working now ... Tables hashtags and status_hashtags have entires now and I could see the postings on PixelFed.

Discover:

![firefox_2019-04-27_09-07-15](https://user-images.githubusercontent.com/8462728/56843510-f6379b80-68cb-11e9-9101-2dec6fe89a88.jpg)

Hashtag "cool":

![firefox_2019-04-27_09-07-28](https://user-images.githubusercontent.com/8462728/56843516-02235d80-68cc-11e9-9ab4-30c303179a67.jpg)

**Comment by c3x** [comment]
Ok, did a new post and the same "issue" again. Could it be that it takes 24 hours to the hashtags be visible?

**Comment by c3x** [comment]
Hashtags and create of thumbs are working, when I start manually "php artisan queue:work" from shell.

**Comment by FranzShaach** [comment]
Just had this issue too (Pixelfed 0.9.4, PostgreSQL 10.8, PHP 7.3):
`DETAIL:  Key (slug)=(lyon) already exists. (SQL: insert into \"hashtags\" (\"name\", \"slug\", \"updated_at\", \"created_at\") values (Lyon, lyon, 2019-06-16 09:15:32, 2019-06-16 09:15:32) returning \"id\") at /usr/local/www/pixelfed/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 23505): SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint \"hashtags_slug_unique\"
`
I used #lyon (all lowercase) for a few posts with no problem, and #Lyon for the last one: tags were not recognized (not clickable) and the post did not appeared in my Mastodon timeline (I'm following my Pixelfed accounts with my Mastodon account).

**Comment by raphgilles** [comment]
Same issue for me !

**Comment by lapineige** [comment]
Kind of the same here:
Yesterday I posted pictures with "WeeklyPhotoChallenge" as an hashtag, without any problem.
Today it doesn't work, and it breaks all other hashtag.
I also tried "Insectes", not working, but "insectes" is.
