### ISSUE TITLE
Remote Interaction (Like Mastodon URL)

### ISSUE THREAD

**Issue by IsserTerrus** [pixelfed/pixelfed#1276]
To make a remote interact, we could use URL on Search Input but it's a little bit hard for newbies.

Mastodon purpose a direct URL : 
https://exemple.com/authorize_interaction?uri=URI_DISTANT_TOOT
https://exemple.com/authorize_interaction?acct=Account@Instance.ext

If we use same endpoint, we could help plug-ins maker to remote interact to our Toots, Articles, Pictures ...

**Comment by trwnh** [comment]
This is essentially a question of cross-domain authentication. At the most basic level, we can simply redirect the user to their host domain, but IMO I think the way Mastodon handles this redirect is not ideal. More thought needs to be put into how best to handle cross-domain actions and remote authentication -- especially how to handle this in a standard way that makes sense for other softwares.

Personally I think an approach similar to OpenWebAuth would actually be more useful, so that actions could be performed without having to redirect at all. This would make the user experience feel more "native" instead of being bounced around different domains.

**Comment by dansup** [comment]
Shipped in 4ca7c6c3
