### ISSUE TITLE
Why is it that hashtagging numbers doesn't work #hashtag #tag #year

### ISSUE THREAD

**Issue by jantheodor** [pixelfed/pixelfed#1505]
I use hashtags to filter my images by year (amongst other things), like #1999, yet this doesn't work on pixelfed and I've been wondering why that is? And how about making it work? Thanks for the answer.

**Comment by trwnh** [comment]
it's an issue with twitter-text. numbers aren't turned into hashtags because the "hash mark" is the same as the "number sign", and people frequently type out numbers not expecting them to turn into tags. changing this would require replacing twitter-text with our own regex, which is currently not something we want to do.

closing this as wontfix for now, but may reopen later.
