### ISSUE TITLE
Make it possible to edit the first comment

### ISSUE THREAD

**Issue by lhirlimann** [pixelfed/pixelfed#1528]
Take this post https://pix.diaspodon.fr/p/Usul/17255899244662784 , I forgot to add a "first comment - enhanced description" - If I edit the post I can only edit the photo's description I can't edit the first comment. Would it be possible to do so?

**Comment by okpierre** [comment]
The best way is to delete and post again

**Comment by trwnh** [comment]
Deleting and reposting is only a temporary workaround -- I do think we should plan on supporting editing captions. This has been previously discussed in #823 FWIW, but some more thought needs to be given to exactly how editing would work if implemented. If we plan to track diffs or old versions of Objects, then it would require a significant refactoring. If we simply add an "edited" indicator, it would not be so significant.

IMO the only real issues with editing posts are that boosts/likes might be perceived to only reference the old Object and not the updated version. With likes, it's not such a big deal -- likes can be hidden or ignored or whatever. But boosts are more fundamentally complicated because you are effectively drawing attention to something that is outside of your control -- you are letting people embed arbitrary content on your pages. The only way around this is to either cache a static copy at the time of the boost, like archive.org or Tumblr, or to not support boosts at all.

BTW I'm reposting this there and reopening that issue since the conversation is more fleshed out in the other issue.
