### ISSUE TITLE
Allow inbox to receive Image posts

### ISSUE THREAD

**Issue by GidiKroon** [pixelfed/pixelfed#1642]
I understand why the activitypub inbox can receive a Note object, if it has a visual attachment, since that is what Mastodon sends. But I was surprised to see in the code that the much more fitting Image object type is dropped completely.

See https://www.w3.org/TR/activitystreams-vocabulary/#dfn-image

It would be great if Image object types are accepted as well, with the same restrictions about having valid attachments of course.

**Comment by trwnh** [comment]
would need a transformer to convert Create Image into a status.

currently we support Create Note with `attachment` [Image,Video]. the `content` of the Note becomes the status text, and other metadata of the Note gets converted similarly. but when consuming a Create Image activity, there is not a clean mapping. for example, do we instead convert `name`, even though this is more akin to a title than a caption? do we limit ourselves to Image with Note attached, like we do Note with Image attached? is any other software currently generating such activities, so that we may strive for compatibility with them? such questions need answering.

**Comment by GidiKroon** [comment]
I was thinking that where currently the test is 'type=Note' it could be changed to 'type=Note or type=Image', without handling these posts differently (for now). The spec doesn't say it is invalid for type=Image objects to have a content attribute with text in it and an attachment attribute with links to images.

The only software I know that could generate such posts is the ActivityPub plugin in Wordpress. It (optionally, and not the default) does like I described: generates the same object with content and attachment etc, except sets type to Image instead of Note or Article. However, the default is to fix the type to Note, so for most users that have not tinkered with the settings it will just work.

See: https://github.com/pfefferle/wordpress-activitypub/blob/master/includes/class-post.php

It is of course also possible that that implementation is wrong. It is also in the 0.* phase...

But you're right. It is more logical that instead of the current 'Create-Image with attached Image-Link' it would send a 'Create-Image with Link', which would need different handling.

**Comment by dansup** [comment]
We already support Image. 

https://github.com/pixelfed/pixelfed/blob/5eda09cbf6cd2bea7e24fdcbe414f8e68e9ef99b/app/Util/ActivityPub/Helpers.php#L59

**Comment by GidiKroon** [comment]
So as attachments to a Note object? Fair enough, as long as it is clear that that is what applications need to send. Thanks for your time!
