### ISSUE TITLE
Backfill old statuses on remote follow

### ISSUE THREAD

**Issue by ahstro** [pixelfed/pixelfed#1745]
Got around to setting up my own instance the other day, and since every account I know is on a different instance, I set out on a following spree. However, I couldn't see any posts but my own in the timeline, until today when one of the accounts posted a new image.

### Steps to reproduce:
1. Setup instance
2. Enable federation
3. Follow remote account with posts
4. Be sad about no posts
5. Be happy when they do post something

### Version / instance info:
My account is on [pixelfed.ahst.ro](https://pixelfed.ahst.ro), running `0.10.6` and the remote accounts are on [pixelfed.social](https://pixelfed.social), which I'm pretty sure is currently running `0.10.6` too.

**Comment by trwnh** [comment]
Wait, so what's the issue? You followed remote accounts, then one of them made an image post that you successfully received?

**Comment by ahstro** [comment]
@trwnh No, the issue is that their previous posts don't show up on the timeline, even though they were made only hours before I followed them. My timeline only shows two posts, my own and one made by an account I followed after I followed it, but I follow several accounts, so I should be able to scroll down and see more (I assume?)

**Comment by trwnh** [comment]
Ohhhh. OK, the issue is that there is no backfilling of posts. Posts are only delivered, not fetched, so timelines will only be constructed using available posts. See also https://github.com/tootsuite/mastodon/issues/34 for a similar longstanding issue. Your only option currently is to view their profile directly on their site instead of yours, at least for now.

**Comment by ahstro** [comment]
Ah, that makes sense. I need to do a deep dive into ActivityPub so I get a better sense of what's going on and why. Thanks :)

**Comment by trwnh** [comment]
Well, it's like email. You send a Follow to someone, they Accept your Follow and start sending you any new activities.

Getting *old* activities and objects is a separate mechanism. You can always GET public objects if you know their id, and you can try to GET the outbox, but 1) you need to explicitly request that data (it's not done automatically) and 2) you are not guaranteed a response (since outbox may only be used for transient delivery rather than persistent data). Also, if you want non-public posts that you are authorized to see, then you need some kind of cross-domain authorization like #1276

**Comment by dansup** [comment]
@ahstro You can fetch old posts by searching the post URL. 

We do not plan to add backfilling on follow because we are disabling outboxes for privacy reasons.

**Comment by limdingwen** [comment]
I would like to request re-opening this issue for UX reasons, similar to the issue on Mastodon.
