### ISSUE TITLE
ImageResize and AvatarOptimize fail

### ISSUE THREAD

**Issue by matrix07012** [pixelfed/pixelfed#1759]
I'm using ImageMagick and both ImageResize and AvatarOptimize fail for me because they can't write image data to path.

![image](https://user-images.githubusercontent.com/8049717/66203292-47805e00-e6a8-11e9-8b51-c902ae20ff69.png)
![image](https://user-images.githubusercontent.com/8049717/66203322-61ba3c00-e6a8-11e9-83fd-105513245f56.png)
![image](https://user-images.githubusercontent.com/8049717/66203348-71d21b80-e6a8-11e9-8558-0bb18229399b.png)

**Comment by dansup** [comment]
@matrix07012 That looks like a permission issue. ```bootstrap/cache``` and ```storage/``` need to be writable by the webserver user and horizon user.

**Comment by matrix07012** [comment]
It looks like deletes fail too, but I tried manually writing to bootstrap/cache and storage/ as user www-data and as user pixelfed who owns the directory and it works, however the jobs still fail.

**Comment by trwnh** [comment]
Can you run `ls -la` on that directory at storage/app/public/m/uuid? 

To be clear, permissions must be correct for both the **web user** and the **app user**:

- web (www-data) should have permission to read and write (because requests are only delegated to php-fpm, and still owned by this user)
- app (pixelfed) should have permission to read and write (because background task queues are run with this user, e.g. generating thumbnails and optimizing avatars after they were written there by the web user)

I'd say your group permissions are incorrect. Depending on how you set up your "default group" when creating your users, you may also have to run `chmod -R g+s` on your pixelfed install so that newly-written files inherit the group from the parent folder rather than from the user who wrote them.

**Comment by matrix07012** [comment]
@trwnh 
UUID folder (currently only one user) and everything in it is owned by www-data and only the owner has write permissions.
User pixelfed belongs to groups pixelfed and www-data and user www-data belongs to groups www-data pixelfed.
