### ISSUE TITLE
PixelFed logo

### ISSUE THREAD

**Issue by hellcp** [pixelfed/pixelfed#177]
~~It would be nice to create logo for PixelFed, as rn we are using no favicon and generic camera to identify it ;)~~

The logo contest is in #182, its still open!

**Comment by hellcp** [comment]
In addition it might be worth to consider guidelines and font choice in regard to brand, as it will be easier to create recognizable artwork and other stuff based on that.

**Comment by hellcp** [comment]
My suggestion was this:

![pixelfed-logo](https://user-images.githubusercontent.com/30577011/40888928-db33d1e2-675e-11e8-87c8-b74b19fa5d98.png)

or

![pixelfed-logo](https://user-images.githubusercontent.com/30577011/40889103-21d35c4c-6761-11e8-9690-57a6a15654d0.png)

**Comment by moshpirit** [comment]
![](https://i.imgur.com/dhnKsXo.png)
![](https://i.imgur.com/B3vLwwr.png)
![](https://i.imgur.com/mpxuUdG.png)
![](https://i.imgur.com/m64W07u.png)

I'm also doing another with the camera "pixel art" styled. Like real pixel art, not the first logo, wich is basically a camera made of pixels with degradation. 

I can change the colours though, I just worked with this schema because it feels more like Instagram at the beginning and just didn't change anything.

**Comment by wakest** [comment]
what about something using the idea of being fed pixels one at a time. I was thinking something like this when the idea of making a logo started being discussed.
<img width="258" alt="screen shot 2018-06-03 at 8 58 25 pm" src="https://user-images.githubusercontent.com/7890201/40890117-35f3d124-6771-11e8-8259-c6763f6f3b3a.png">
this image is [CCBY](https://thenounproject.com/search/?q=mouth&i=372890) by Sergey Demushkin, RU

**Comment by wakest** [comment]
heres another take on that idea:
<img width="401" alt="screen shot 2018-06-03 at 9 04 09 pm" src="https://user-images.githubusercontent.com/7890201/40890156-b44a935a-6771-11e8-9ffb-93ceb9fe051a.png">
[CCBY](https://thenounproject.com/search/?q=mouth&i=230336) by Leszek Pietrzak, PL

**Comment by moshpirit** [comment]
Isn't the idea of the logo to reproduce what is PixelFed actually? For me, when I see these logos I think in restaurants hahaha but it's just my view. This is why I keep using a Camera and the share icon, since to me, PixelFed is that preciselly: different cameras and the importance of sharing information

**Comment by wakest** [comment]
Ohh another idea I just had based on the name PixelFed is Pacman eating an Instagram like logo.
<img width="872" alt="screen shot 2018-06-03 at 9 47 45 pm" src="https://user-images.githubusercontent.com/7890201/40890521-d62234aa-6777-11e8-8757-418876b746f5.png">

**Comment by wakest** [comment]
@moshpirit there is no way of having a recognizable camera icon these days I fear. search camera on any app store and there are thousands of variations on the same theme.

**Comment by dansup** [comment]
Thanks for the logos everyone!

**Comment by hellcp** [comment]
@wakest exactly the reason why I went with a thing that is not a camera, but very simplified "hands" framing a "pixel".

**Comment by Gargron** [comment]
I like @moshpirit's top right a lot, it feels quite unique.

**Comment by faissaloo** [comment]
I like @hellcp's 4th one

**Comment by dansup** [comment]
The logo contest is in #182, its still open!
