### ISSUE TITLE
Album posts in Collections are missing album overlay

### ISSUE THREAD

**Issue by jwildeboer** [pixelfed/pixelfed#1826]
When I add a post with multiple pictures to a collection, only one picture is actually added to the collection.

Solution: Adding a post with multiple pictures to a collection should result in all pictures of that post being added to the collection.

**Comment by jwildeboer** [comment]
Correction. Seems it is only a problem of displaying the content of a collection. There is no indication that an entry in a collection contains more than one picture. You have to click on the entry in the collection to be redirected to the post where you can view all pictures.

Solution: Indicate in the collection view when an entry has more that one picture or just show all pictures in the collection view.

**Comment by jwildeboer** [comment]
Example: My collection at https://pixelfed.social/c/101995278990708736 does not indicate that it actually are three pictures.

**Comment by trwnh** [comment]
Collections are a group of posts, not of their pictures. They're not galleries. I think the real issue is that you can't tell which posts are albums from the thumbnail.

This could probably be fixed by adding an overlay indicating the total number of pictures in an album post? EDIT: Actually, there's already an overlay that's shown on profiles. This overlay should be generalized to all thumbnails as a component.

![image](https://user-images.githubusercontent.com/10606431/69054204-b56eb380-09d0-11ea-88c7-711a32c345ba.png)

![image](https://user-images.githubusercontent.com/10606431/69054114-88220580-09d0-11ea-9c76-f01aff6cef3b.png)

![image](https://user-images.githubusercontent.com/10606431/69054158-a38d1080-09d0-11ea-9db1-fa931b9fa47e.png)

**Comment by trwnh** [comment]
Seems to have been fixed at some point, not by marking album posts, but by simply showing all photos in the album post separately in the collection...
