### ISSUE TITLE
Location is far from being complete/correct.

### ISSUE THREAD

**Issue by lhirlimann** [pixelfed/pixelfed#2068]
I have encountered two issues with Location, when I want to add location to a picture.
Grisolles is not a unique name for France, but I'm only being offered one (and I don't know if it's mine or the other one) :
* https://fr.wikipedia.org/wiki/Grisolles_(Tarn-et-Garonne)
* https://fr.wikipedia.org/wiki/Grisolles_(Aisne)
National park are not found ; say https://en.wikipedia.org/wiki/Amboseli_National_Park is nowhere to be found.

**Comment by dansup** [comment]
@lhirlimann We are using a location dataset that is limited to cities with populations of over 5000 people. Because places federate, we can't add support for custom locations without requiring some kind of validation to prevent abuse.

I know it's not an ideal situation, will keep this issue open until we decide on a path forward.

**Comment by prolibre** [comment]
@dansup Wouldn't it be possible to migrate to cities with populations of over **1000** people ? There are many places missing in the countryside. Thanks for your work.

**Comment by eliasp** [comment]
Alternatively, also import administrative districts, which would allow to at least tag the rough area of a location…

This might be also preferred by those who don't want to expose too fine-grained location data in their posts due to privacy reasons.
