### ISSUE TITLE
API: Liking/Disliking causes 500 error

### ISSUE THREAD

**Issue by dobios** [pixelfed/pixelfed#2088]
Hi, while working with the `api/v1/statuses/:id/favourite` and `api/v1/statuses/:id/unfavourite` endpoints I caused a peculiar bug:

- If a status is liked via the API and then unliked (also via the API) it results in itreturning a 500 error code. Then afterwards, trying to unlike the post on the website (I tested everything on pixelfed.de) also causes an error of the same nature.

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
I could reproduce this, liking, unliking then liking again with the API caused a 500 for me. Then in the web client this happens when trying to press the like button:
![afbeelding](https://user-images.githubusercontent.com/61561059/77112682-b6206080-6a29-11ea-8488-421161d3cba2.png)

Maybe some kind of abuse protection triggering?

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
The only thing I could see in the API controller is this: https://github.com/pixelfed/pixelfed/blob/dev/app/Http/Controllers/Api/ApiV1Controller.php#L1210
Maybe something about the LikePipeline doesn't like this?

**Comment by dansup** [comment]
I have fixed the issue in 01525cb, the bug was caused by improperly soft deleting likes. 

**Admins will need to run a command to fix affected data, it will be released in the next version!**

**Comment by LynoForWindows** [comment]
Problem Fixed
