### ISSUE TITLE
Unable to follow Mastodon bots

### ISSUE THREAD

**Issue by raphgilles** [pixelfed/pixelfed#2098]
Hello,

This is not the first time that I tried to follow a bot from Mastodon, but the search found nothing.

Can you think it could be possible to enable the possibility to follow bots in the future ?

Thank you !

**Comment by trwnh** [comment]
this is probably because they are presented as `Application` or `Service` instead of as `Person`

potentially relevant areas of code:

https://github.com/pixelfed/pixelfed/blob/d07b80da433d8ba12ff8aafeaf5d6dc5488300da/app/Http/Controllers/SearchController.php#L42-L44

https://github.com/pixelfed/pixelfed/blob/83686336eb597d8d7761745cb6697bbfd9480585/app/Util/ActivityPub/DiscoverActor.php#L38-L48

https://github.com/pixelfed/pixelfed/blob/26c47a0d3ac2296228398f623fd734fb9b2ceb23/app/Util/ActivityPub/Inbox.php#L300

https://github.com/pixelfed/pixelfed/blob/26c47a0d3ac2296228398f623fd734fb9b2ceb23/app/Util/ActivityPub/Inbox.php#L308-L309

**Comment by dansup** [comment]
Fixed!
