### ISSUE TITLE
Add different 'like' types

### ISSUE THREAD

**Issue by NFGman** [pixelfed/pixelfed#22]
Liking things is great, but often I'd like to like something ironically, or just acknowledge that I've seen it.  Facebook sort of expanded on the 'like' functionality by adding several emojis, but what if an emoji-picker was used to allow any single emoji to be used when liking a post?

Star.  Heart.  Mermaid.  Skull.  X mark.  Check mark.  Warning icon.  Country flag.

One single character could allow much more subtlety and greater expression.  And a single emoji doesn't take a whole lot of space, and most users will be using phones or a web interface with an emoji picker already...  Store the user's default like-on (like icon, hehe), along with the instance's default, and recently used...

**Comment by wakest** [comment]
Misskey (a microblogging service that supports ActivityPub) has implemented reactions. It seems they only federate them with other Misskey servers at the moment cause other ActivityPub services have not yet implemented reactions, but I am pretty sure they would love to do it in a common way so it would federate across services.
[Here](https://github.com/syuilo/misskey/blob/master/src/remote/activitypub/kernel/like.ts#L24-L28) is where they implemented reactions. [Here](https://misskey.xyz/notes/5b0e92eae791ae37cb48c60f) is the thread I was chatting with the [dev](https://github.com/syuilo/misskey/) about it.

**Comment by ghost** [comment]
I personally dislike like types because I feel like they replace commenting with a more impersonal/shallow engagement but I recognize not everyone feels this way

However I would be interested in talking about how we would moderate this? Likes are generally not moderated, everyone who hasnt been blocked by the original poster can leave one and liking posts is generally not considered harassment, because well, you just liked it. But what if someone started leaving 🔪’s on all of your posts? There would need to either be a limited set (a la facebook) or the ability to report reactions the way comments can (will be able to be?) be reported.

**Comment by NFGman** [comment]
I'm surprised it's not considered harassment.  If I see someone who's stalking me leave a 'like' I'll know they're still there, in my orbit, looking at my stuff.  That reminder is harassment enough, IMO.  

I don't know how PF is handling this against comments (silencing, blocking, etc), but it seems logical that the same mechanism can be applied to likes.

As for discouraging comments...  Well, yeah, it will have an impact, but it'll also open up a wealth of new communication options.  A wink between two parties can impart worlds of information.  Friends who can like in different ways could, with a single character, do the same.  People who might not have commented could drop a 💪 or 💄 or ❄️.  A whole new sidechannel.

**Comment by ghost** [comment]
Yeah I was mostly noting it for the sake of disclosing potential bias sort of ‘i dont like this feature so i may be being unnecessarily harsh’ kind of thing (i dont think it adds an actual new communication option though, considering you already can leave single emoji comments, what it’s doing is promoting a preexisting communication option. And then the question is ‘which of these methods of communication should be prioritized’ which is where I come down on the side of comments. However I’m not actually trying to argue against implementation so I’m gonna drop this particular line of conversation)

To clarify on likes & harassment, i mostly meant theres rarely an occasion to report a user over likes? Either it can be solved by blocking, or its uncomfortable due to past bad behavior by the harasser, in which case that behavior should be whats reported to the mods. Whereas in my 🔪 example, the emoji reaction on its own can be harassment, and therefore that specific interaction needs to be reportable - this is probably not very hard from a code perspective, where likes and comments are treated very similarly as i understand? But I’ve been struggling to figure out a good way to implement it on the user side of things

**Comment by vilbi** [comment]
From UI perspective ceep it simple and most important neutral!
- replace the like ❤️ with a pixelfed specific fav icon like 📷 with a ⭐ in the Lens.

**Comment by faissaloo** [comment]
Absolutely do not add this, it's severe feature creep and adds unnecessary complexity

**Comment by dansup** [comment]
This would not federate with existing AP software, it is not covered by the spec.
