### ISSUE TITLE
[UI] post description looks like comment/redundant user name

### ISSUE THREAD

**Issue by encarsia** [pixelfed/pixelfed#240]
In both (timeline and post) views the post captions look like comments. This also results in the user name displayed twice, at the top of the post and in the description below. I think this is improvable.

Maybe the caption could be discreetly/visually separated in a shaded box or the like without showing the user name again.

![post view](https://user-images.githubusercontent.com/16634394/41190416-50a0c394-6bde-11e8-9c1d-d7bc18905d13.png "post view")

![timeline view](https://user-images.githubusercontent.com/16634394/41190415-4ede107a-6bde-11e8-9e5a-f1dfb269f1da.png "timeline view")

**Comment by hellcp** [comment]
That's done in the same way as Instagram does it ;)

**Comment by encarsia** [comment]
That is an explanation, not an excuse...;)

**Comment by faissaloo** [comment]
I agree with @encarsia, it really does need seperation

**Comment by thomas-kuntz** [comment]
I agree that the caption needs to be easily distinguishable from the comments.

What's more, when there is no caption the username is displayed twice with an empty caption. Displaying the caption in a separate shaded box would allow to remove the username and thus avoid this.

<img width="373" alt="screen shot 2019-02-12 at 7 33 13 pm" src="https://user-images.githubusercontent.com/16361470/52659347-5e95f400-2efd-11e9-93bb-6c39c7646ebc.png">

As a side effect, when someone posts a comment on a post that doesn't have a caption, the same weird thing happens: the username and the empty caption is still displayed above the comments. It's weird.

<img width="375" alt="screen shot 2019-02-12 at 7 33 29 pm" src="https://user-images.githubusercontent.com/16361470/52659500-ad438e00-2efd-11e9-874f-86a4f1066d85.png">

**Comment by trwnh** [comment]
there should definitely be more discussion around breaking with certain design decisions just because "instagram does it that way". i am reminded of this tumblr redesign concept: https://medium.freecodecamp.org/after-teaching-myself-to-program-i-wanted-another-challenge-so-i-redesigned-tumblr-69ca39f62bad

namely, that the post layout should be altered to fit the expectations of users and not purely to follow convention. with that in mind, the post header looks a little sparse with just the username and the three-dot menu, so maybe the caption could be moved into it instead of being replicated in similar style to the comments? also, for the vertical view, the header can be moved below the photo and above the action buttons.

extremely quick and lazy mockup: 
![image](https://user-images.githubusercontent.com/10606431/52678964-0a891080-2ef9-11e9-8c4e-b9c278a382ea.png)

with a tiny bit more styling, perhaps:
![image](https://user-images.githubusercontent.com/10606431/52679098-9438de00-2ef9-11e9-8c26-531b52fe7776.png)

or maybe something like this:
![image](https://user-images.githubusercontent.com/10606431/52679394-92bbe580-2efa-11e9-9229-441fbc9bec39.png)

**Comment by thomaskuntzz** [comment]
Yes, it definitely looks better like that!

**Comment by thomas-kuntz** [comment]
Yes, it definitely looks better like that!

I still wonder about this 'new UI' I read about on Mastodon: https://mastodon.social/web/statuses/101232877790019192

I can't find any trace of it here on GitHub, but if there's a new UI coming out soon, then will it replace the current one? If not, will two different UIs be available? How will that be managed? I think it would be good to know a little bit about that before setting out to work on the current UI.

Does anyone know more than me about this?

**Comment by trwnh** [comment]
@thomaskuntzz That's Micro UI, a Tumblr-inspired frontend that is currently in development but unreleased

**Comment by trwnh** [comment]
One other related UI issue I noticed today: with the 3dot menu being at the top of the post and the comments being at the bottom, it's hard to access post actions when reading comments. At minimum, the post menu should be moved down to the same row as the post actions. And with the username duplicated at the top and in the caption, it makes more sense to remove the top header.

**Comment by dansup** [comment]
Fixed in latest commits.
