### ISSUE TITLE
Artisan and user functions doesn't work (QueryException)

### ISSUE THREAD

**Issue by mauri5hut** [pixelfed/pixelfed#2465]
I cannot use Artisan and the user functions. First was trying to make user admin, but I got the same error when using the "show" function:

-------------------------------------------------------------------------------
 Illuminate\Database\QueryException 

SQLSTATE[22P02]: Invalid text representation: 7 FEHLER:  ungültige Eingabesyntax für ganze Zahl: »myuser« (SQL: select * from "users" where ("username" = myuser or "id" = myuser) and "users"."deleted_at" is null limit 1)

at vendor/laravel/framework/src/Illuminate/Database/Connection.php:671
667|         // If an exception occurs when attempting to run a query, we'll format the error
668|         // message to include the bindings with SQL, which will make this exception a
669|         // lot more helpful to the developer instead of just the database's errors.
670|         catch (Exception $e) {
**671|             throw new QueryException(**
672|                 $query, $this->prepareBindings($bindings), $e
673|             );
674|         }
675| 

+14 vendor frames 
15  app/Console/Commands/UserAdmin.php:42
Illuminate\Database\Eloquent\Builder::first()

+14 vendor frames 
30  artisan:37
Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

-------------------------------------------------------------------------------

PF Version: 0.10.9
Using Postgres as Database.

**Comment by cydactyl** [comment]
Having this same issue, seems to be trying to compare an int with a string, but not familiar enough with php to fix.

**Comment by ghost** [comment]
Having basically the same issue... I want to promote a user to admin,but artisan is failing. In fact the SQL statement is messed up: 

Artisan tries to do this: 

`select * from "users" where ("username" = ij or "id" = ij) and "users"."deleted_at" is null limit 1` 

First, there are some syntax issues: 

1. In PostgreSQL column names are not within "" quotes. In fact, I don't think that Postgres likes double quotes at all. 
2. instead of the columns the values/strings should be quoted like username='ij'

When looking at the table definition, you can also spot another issue: 

```pixelfed=# \d users
                                             Table "public.users"
      Column       |              Type              | Collation | Nullable |              Default
-------------------+--------------------------------+-----------+----------+-----------------------------------
 id                | bigint                         |           | not null | nextval('users_id_seq'::regclass)
 name              | character varying(191)         |           |          |
 username          | character varying(191)         |           |          |
 email             | character varying(191)         |           | not null |
 password          | character varying(191)         |           | not null |
 remember_token    | character varying(100)         |           |          |
 is_admin          | boolean                        |           | not null | false
 email_verified_at | timestamp(0) without time zone |           |          |
 created_at        | timestamp(0) without time zone |           |          |
 updated_at        | timestamp(0) without time zone |           |          |
 deleted_at        | timestamp(0) without time zone |           |          |
 2fa_enabled       | boolean                        |           | not null | false
 2fa_secret        | character varying(191)         |           |          |
 2fa_backup_codes  | json                           |           |          |
 2fa_setup_at      | timestamp(0) without time zone |           |          |
 status            | character varying(191)         |           |          |
 delete_after      | timestamp(0) without time zone |           |          |
 profile_id        | bigint                         |           |          |
 language          | character varying(191)         |           |          |
 has_interstitial  | boolean                        |           | not null | false
 last_active_at    | timestamp(0) without time zone |           |          |
```
In the query the column "id" is reference as a field for a user related name, but "id" is bigint, so this won't work at all. Instead either "name" or "email" should be used, I think. 

The following SQL query does work, though, depending of what the original intention with "id" was: 

`select * from users where (username='ij' or name='ij') and deleted_at is null limit 1;`

But I think it should be enough to query the username alone, so it would be: 

`select * from users where username='ij' and deleted_at is null limit 1;`

Another issue is, that querying all fields by "select *" should be avoided. If you need some result being reported back, I think using "id" as the primary key should be enough. This make: 

```pixelfed=# select id from users where username='ij' and deleted_at is null limit 1;
 id
----
  2
(1 row)```

Hope this helps...

**Comment by Gxnfvhg** [comment]
Open /pixelfed/app/Console/Commands/UserAdmin.php and change every instance of "id" to "name" to fix this problem !!!!
