### ISSUE TITLE
Postgresql - Case issues with pixelfed remote accounts

### ISSUE THREAD

**Issue by jk-na** [pixelfed/pixelfed#2520]
As per short discussion via IRC, some of the active pixelfed.social accounts that I follow from my pixelfed instance are not federating out to my timeline.  It seems that in each case the username on pf.s contains at least one uppercase letter.

If I search from my instance for the user matching the case on their profile, no results are found.

If I search for the user using lowercase the profile is returned and I can follow, however, I don't receive their posts.

So there seems to be a potential case mismatch issue with pixelfed federations, possibly only for instances using postgresql do to its case sensitivity.

**Comment by inga-lovinde** [comment]
It seems that pixelfed converts all remote usernames at some point for some reason, but does not do it early enough.

As a result, it seems that when these users attempt to interact with pixelfed posts, pixelfed tries to find them in DB, fails (because they were saved with lowercase before), decides to insert a new entry, and fails (because it already converted them to lowercase at that point). So no interactions from remote users with uppercase letters are possible.

There was a similar bug already half a year: #2290 , they seem to be triggered by the same commit; maybe it's better to not try to convert anything to lowercase?

Not to mention that, since usernames are used as display names in pixelfed, lowercasing them breaks them.

**Comment by poVoq** [comment]
Was this fixed for 0.11 or should it rather be moved to the 0.12 milestone?

**Comment by dansup** [comment]
Fixed!
