### ISSUE TITLE
RemoteAvatarFetch fails because missing region config

### ISSUE THREAD

**Issue by maste9** [pixelfed/pixelfed#2669]
After updating my instance (docker-image based) to 0.10.10 I receive failed jobs in Horizon like:

```
App\Jobs\AvatarPipeline\RemoteAvatarFetch
ID
50272e0f-a936-4368-ad7a-4b83db1dd8ff
Queue
default
Attempts
3
Retries
0
Tags
App\Profile:265564912762359808
Failed At
2021-02-18 10:46:18

Exception

InvalidArgumentException: Missing required client configuration options:
--
 
region: (string)
 
A "region" configuration value is required for the "s3" service


```
As expected the instance shows no avatars for remote profiles.

I don't understand if this is a configuration I have to do for the instance - which is by the way not using amazon s3 - or if this is a missing tag in the json of the transmitted avatar?

Maybe you can give me a hint what may be missing in my instance's config?

**Comment by maste9** [comment]
OK, Matrix channel says that remote avatar depends on s3 by now?

https://matrix.to/#/!dSVFUbUBfXIgduyxBO:matrix.org/$1613853377387016vlRRc:matrix.org?via=matrix.org&via=chat.coupou.eu

**Comment by inga-lovinde** [comment]
Indeed it seems that for some reason avatars are always stored in cloud: https://github.com/pixelfed/pixelfed/blob/v0.10.10/app/Services/MediaStorageService.php#L214

I wonder why? Pixelfed is a decentralized platform, everybody is supposed to be able to run it on their own hardware, but now they have to use a centralized AWS in order to get avatars to work?
