### ISSUE TITLE
Undefined index: attributedTo at Helpers.php

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#2676]
Pixelfed v0.10.10 https://github.com/pixelfed/pixelfed/commit/2ff863fa0064161e772fc7bc73a729d319b9f5d6 / PHP 7.4.15

```
ERROR: Undefined index: attributedTo {"exception":"[object] (ErrorException(code: 0): Undefined index: 
attributedTo at /pixelfed/app/Util/ActivityPub/Helpers.php:341)
```

stacktrace https://pastebin.com/uxdKeKsU

**Comment by trwnh** [comment]
did you run migrations?

**Comment by okpierre** [comment]
This was fixed but has reappeared. I believe @jk-na also encountered this issue after the fix.

**Comment by jk-na** [comment]
I believe so, however I've just gone through each of the failed jobs since I updated to the latest commits about 3 days ago and it hasn't appeared since. That's not to say that the fix re-reverted and is now working, it just means that probably the condition to trigger it hasn't been met.

I am seeing errors which were apparently fixed a few commits ago, though in most cases I never saw them actually fixed.

**Comment by trwnh** [comment]
i'm going to close this under the assumption that it's no longer occurring; if it does reoccur, please let me know so i can reopen the issue

from what i can see, it has something to do with trying to parse the `attributedTo`, but for some reason an activity was received that didn't contain `attributedTo`?
