### ISSUE TITLE
change URL/domain

### ISSUE THREAD

**Issue by rocky-III** [pixelfed/pixelfed#2707]
Need some help.
Had to change the URL of my pixelfed installation… 
did changes in Nginx and the .env file 

and did

        php$phpversion artisan config:clear
	php$phpversion artisan config:cache
	php$phpversion artisan route:clear
	php$phpversion artisan route:cache
	php$phpversion artisan horizon:purge

Now everything seams to work fine with the new URL but on the pages 

/accont-name

and

/discover

the images thumps are not showing up. If I click on them the main images is visible as it should.

So there seams to be one more setting that hast to be adjusted. Can some one help ? THANKS

all new upload are working 100% also with the  thumps

**Comment by cytrinox** [comment]
I've the same problem with 11.2. Have you found a solution?

**Comment by rocky-III** [comment]
NO - i finally did a new install :-(

**Comment by trwnh** [comment]
there are some major issues with pixelfed installations to support changing the domain name.

- media paths would have to be migrated in the database, which is a very expensive process
- federation would break entirely, as object ids depend on the domain name

it is not currently planned to support domain name changes, so please make sure to choose a stable domain name before installing pixelfed.

for this to change, we would need to support a "disable federation" feature for running pixelfed purely as a selfhosted local-only service. we would probably also need to re-architect the database so that media paths are relative and can handle both S3 and local storage while also handling changes.

**Comment by rudolphh** [comment]
> NO - i finally did a new install :-(

And basically lose everything?
