### ISSUE TITLE
Can’t upload videos on iOS

### ISSUE THREAD

**Issue by azuredusk10** [pixelfed/pixelfed#2745]
Uploading a video from iOS results in the following error, regardless of which video file type I upload: 
![2520B01B-F4A3-4C88-A87A-9F67F428E1A2](https://user-images.githubusercontent.com/18142893/116777895-b7162500-aa66-11eb-808f-80b8eddb4bbb.png)

Steps to reproduce: 
- Press “new post”
- Select “Photo library”
- Choose any video and press “Add”
- iOS will display a progress bar with the title “compressing”
- Once the progress bar is full, Pixelfed displays the error message that the file type is not supported. 

This occurs regardless of which file type I upload - uploading an MP4 file or a video file produced by the native camera app generates the same error. I have the feeling that the photo library converts the video into another format when you press “Add” with no option to disable it. 

iOS 14.4.2, iPhone 11, Pixelfed v10.10
Firefox for iOS

**Comment by ghost** [comment]
@azuredusk10


I managed it to get it worked video finally works but the fact is it works only when you update the env file at once so make sure at glance when you open the env for the first time after installation you add the media types and do all other changes on env at once! And save changes after on terminal clear the cache using the command php artisan and restart the app (this behavior should automatically log you out of your instance that makes sense that the change has taken effect!)

Blah please provide me some reputation for opting this out

**Comment by ghost** [comment]
After adding the media types on env run the following 

php artisan cache:clear

**Comment by azuredusk10** [comment]
Thanks for your response - I hope this can help someone who manages a Pixelfed instance.

I logged this bug as an end user of pixelfed.social so I don’t have access to run commands. I’m not sure if this is a bug on all instances, or if the admin of that particular instance needs to run this command in order to fix the bug. It sounds like it’s specific to this instance if that command fixes this bug

**Comment by ghost** [comment]
@azuredusk10 

take a look on my site
https://spacemag.xyz i had added it
 yes it needs to be added manually unless @dansup the developer of pixelfed adds it on the next update by June 14th hoping he will add it decision is up to him

**Comment by azuredusk10** [comment]
@deez17
Thanks very much for your reply. 
I finally got round to testing uploading a video from iOS on your instance and it works perfectly. I could upload a video recorded from my iPhone into a new post on your instance with no error about an invalid file type. Edit: although no thumbnail was generated for the video. 

Sadly, pixelfed.social still gives me the invalid file type error when I try to upload the same video. 

@dansup  if the fix is as simple as @deez17 makes out, would it be possible to run that command for pixelfed.social? I, and perhaps many other iOS users, would be very grateful to be able to upload videos. 

Thanks for your help!

Edit: Is there any known way to generate a thumbnail for the video as well? Here’s my test video: 
https://spacemag.xyz/p/Test345/331927616548376576

**Comment by ghost** [comment]
@azuredusk10 

This is my account you can try scrolling down and searching for videos with thumbnails I had already l uploaded 

https://spacemag.xyz/Space

**Comment by d1gg** [comment]
Same problem here. Adding MIME type 'video/quicktime' in .env file solved it.

**Comment by gangrif** [comment]
I am attempting to implement the additional media types mentioned here.  It doesn't seem to work.  Ive added 
MEDIA_TYPES=image/jpeg,image/png,image/gif,video/mp4,video/mpeg,video/3gpp,video/quicktime
to my env, and cleared the config cache.  even restarted things, seems that pixelfed still see's the original set of media_types 

The ability to upload from IOS really should be a default.

**Comment by NuclearDog** [comment]
For anyone who shows up here in the-year-of-our-lord-2023: Good luck and godspeed.

Full notes below, but my tl;dr for a server operator would be "learn to live with it or leave".

---

I tried the `MEDIA_TYPES` solution and wasn't having much luck. On a bit of digging in, it looks like pixelfed tries to load some config values:

1. From the cache (e.g., redis)
2. From the database's `config_cache` table
3. From Laravel's cache of the .env file

I may be missing something somewhere, but based off of digging through the controllers for the admin UI, it looks like after initial start/setup, you can largely ignore the .env for any [of these values](https://github.com/pixelfed/pixelfed/blob/e286f987626c9349320295b780c7632378333313/app/Services/ConfigCacheService.php#L23). That includes the media types.

So to update this value, go to your database and update the value for pixelfed.media_types in the config_cache table. You'll need to refresh the value in your cache as well. As long as your instance isn't under any sort of heavy load where a cold cache will ruin your day, a `php artisan cache:clear` may do it.

I didn't keep great notes, but looking back it looks like this value is pulled directly in some of the blade templates, in which case you'll need to `php artisan view:cache` as well to recache the views to reflect the new values.

You should be able to upload `video/quicktime` files now!

But... that's not the end of the story.

Nothing else is really going to work for you. The "videos = video/mp4 mime type" assumption is baked in to, and hardcoded across, most of the codebase. So you're not going to get thumbnails, etc.

I did do a quick grep across the codebase for everywhere `video/mp4` was used and updated it to include `video/quicktime` as well and things seem to be largely working now.

The reason I say "don't bother" is:

- The use case I was trialing pixelfed for was unfederated. I have no idea if this breaks anything to do with federation. Some of the code I updated touched on that.
- The overall pattern here is of hardcoding these things across the codebase, so this won't be a simple patch to maintain going forward. You'll basically need to repeat the grep + modify exercise on any updates.
- It looks like there's stalled out work on reencoding all the videos to mp4 instead of dealing with the raw video/quicktime files, so I'm guessing that's the direction they'd like to see the project go and a PR with these changes would probably not be accepted.
