### ISSUE TITLE
HTTP Error 500 and PHP fatal error

### ISSUE THREAD

**Issue by ItchyBugReporter** [pixelfed/pixelfed#2977]
I am using PixelFed 0.11.1 with PHP 7.4.21. I started with PHP 7.3, but upgrade to 7.4 after installing PixelFed.

With PHP 7.3, I was able to successfully install PixelFed, register an account, and post an image.

After upgrading PHP, I get a HTTP Error 500 in my browser, and my server's error log provides the following error:

`2021/10/17 12:59:42 [error] 31955#31955: *5 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method ComposerAutoloaderInit2d30c8591209ca6c834abe03142931fb::getLoader() in /srv/www/youhavewrites/pixelfed/vendor/autoload.php:7
Stack trace:
#0 /srv/www/youhavewrites/pixelfed/public/index.php(26): require()
#1 {main}
  thrown in /srv/www/youhavewrites/pixelfed/vendor/autoload.php on line 7" while reading response header from upstream, client: 0.0.0.0, server: pixelfed.youhavewrites.social, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "pixelfed.youhavewrites.social", referrer: "https://www.youhavewrites.social/"`

(client IP address censored to 0.0.0.0 for privacy)

**Comment by ghost** [comment]
Hello!

hope you are doing well, pixelfed Isn’t  supporting 7.4 or newer versions so far it would probably take a while to the developer on considering supporting newer versions in such cases the best practice is creating a backup so that it’s easier to restore follow the back up process to make sure you don’t loose visitors of your site 


Have a good day!
