### ISSUE TITLE
Make it easier to add image alt text

### ISSUE THREAD

**Issue by Huy-Ngo** [pixelfed/pixelfed#2990]
Currently (v0.11.1), to add alt-text, after finalizing the image you have to:

1. Click "Advanced settings"
2. Click "Media descriptions"
3. Add description and submit

I find step 1 problematic because:

- Adding image description is not "advanced".
- It is not intuitive.
- An extra step discourage users to add alt-text

Suggested solution:

- Put an input for image description in the same popup dialog as caption.
- Has a tooltip explaining why it is important since it can be confused with the caption (the current "Describe your photos for people with visual impairments." is fine)

**Comment by MarcoZehe** [comment]
I support this. I am a blind user who tried out PixelFed for the first time, and I also found the process of adding alternative text rather cumbersome.

**Comment by theotherlinh** [comment]
Agree with this. There seemed to be a huge thing about this on Mastodon and I was surprised Pixelfed seemed to have it as a back-burner item. It's too many clicks to get to media description. Another option is maybe if users select "require media description", then it  brings it to the forefront (though, this feels like it's more work than just moving it to the main input page somehow instead.

**Comment by TinoJ** [comment]
I add an alt-text EACH time and it would indeed be more convenient to have the two "hidden" advanced options just on the same menu like
![grafik](https://user-images.githubusercontent.com/18018490/206036567-7ca5df7a-67fb-4087-9513-1418dd14d5a4.png)

**Comment by gunchleoc** [comment]
One more thing that's very challenging is the character limit. I'd like to have more characters for when I need to create more detailed descriptions.

**Comment by robinlej** [comment]
Is there any plan for this? It's the first thing I noticed when trying Pixelfed.
What's more, I actually didn't find that submenu for my first posts even though I wanted to add captions. In its place, I found another caption menu somewhere else, which only allows 140 characters.

To make things clearer, I think we should:
- Set the captions options on the same level as the main description. (As in Tinoj's example.)
- Remove the other place altogether. (Which appears if you upload more than one pic, then click on the previous arrow, then on "edit" under a pic.)

I'll see if I can lend a hand with the code when I have a bit of time. (But I can't promise.)

[Edit] Turns out there are plans for this among other stuff. See https://mastodon.social/@dansup/109483010946439310

**Comment by mitexleo** [comment]
> One more thing that's very challenging is the character limit. I'd like to have more characters for when I need to create more detailed descriptions.

You can Increase character limit if you want ... from .env

**Comment by filmfreedom-org** [comment]
Strongly support this request.

I use image caption on every post and have the "require image caption" option set.

Which is very clunky when it requires me to go to the advanced menu every single time. Meanwhile, I NEVER use the "Location" option, the "Tag" option, the "License" is always my default, and "Add to Collection" doesn't really work properly from this menu anyway, so I always add the images from the Collections page, anyway. So if space is the issue, there are several candidates to demote to the "Advanced" page.
