### ISSUE TITLE
Multiselecting files to upload not working

### ISSUE THREAD

**Issue by cloo** [pixelfed/pixelfed#2994]
It is not possible to select multiple photos for upload, even if you see a prompt "share up to 50 photos or videos". 
Selecting and uploading 50 photos one by one would be a terrible experience.

**Comment by piebob** [comment]
yes please! i would really love the option to select multiple photos at the same time from the gallery on my phone when posting. this has kept me from posting to pixelfed because it takes so many clicks to post multiple images in a single post. i dislike it when other post many single images one after the other (which i assume they do because it's quicker than trying to post them in a single post) so i don't want to do it myself. upvote!
