### ISSUE TITLE
Clicking profile Website link starting with "http://" instead of "https://" results in an error

### ISSUE THREAD

**Issue by brookmiles** [pixelfed/pixelfed#2996]
pixelfed.social v0.11.1

1. edit profile and enter `https://yahoo.com` for Website
2. view profile and click the link, the page correctly opens
3. edit profile and enter `http://yahoo.com` for Website
4. view profile and click the link, the message "Sorry, this page isn't available." is displayed (`https://pixelfed.social/i/redirect?url=http%3A%2F%2Fyahoo.com`)

**Comment by samuelroland** [comment]
Hey @brookmiles and @dansup,

I confirm there is a bug with this. After a little research, I think that the URL is detected as invalid, because it is not HTTPS (which should be valid IMO).
The `/i/redirect` route seems to use `Helpers::validateUrl($url)` (and return 404 when `false`) which contains this validation:
https://github.com/pixelfed/pixelfed/blob/0c3691efc7eb33a9c54dda952c7a409a2595fb6a/app/Util/ActivityPub/Helpers.php#L157-L159

Is it just a bug ? Or is it an expected behaviour for some security reasons @dansup ??

I would like to do my first contribution to the open-source world, and as I'm learning Laravel and VueJS (beginner and middle level) that seems a good issue to start with...
I'm not a user of Pixelfed (I've just created an account, though), but I would like to contribute to a fediverse software.

What direction should I take to fix it @dansup ? Thanks in advance.

**Comment by dansup** [comment]
@samuelroland Hi, please remove `@click.prevent="remoteRedirect(profile.website)"` from https://github.com/pixelfed/pixelfed/blob/0c3691efc7eb33a9c54dda952c7a409a2595fb6a/resources/assets/js/components/Profile.vue#L148 and use the `staging` branch for your PR. Thanks in advance!
