### ISSUE TITLE
The action bar is now way too big

### ISSUE THREAD

**Issue by faissaloo** [pixelfed/pixelfed#300]
The old size was great, it fit all the icons snugly, now it's wasting tons of space

**Comment by trwnh** [comment]
One thing that came up while I was taking another look at this and #301 -- I don't think the current action bar design is flexible enough to cover adding more actions in the future, because while the height has been reduced via #334 (by https://github.com/dansup/pixelfed/commit/04b22b29d741463090ff897b17e5165975b32200 specifically), there's still the issue of width overflow, and the search bar is awkwardly omni-present.

![image](https://user-images.githubusercontent.com/10606431/43121823-a82419ee-8ee4-11e8-8666-ba4f0829efc2.png)

I think the action bar needs to be split from the header bar and moved to the bottom with `position: fixed` on mobile devices. Here's what this might look like:

![image](https://user-images.githubusercontent.com/10606431/43122344-4aef0246-8ee6-11e8-8869-e02db3401d90.png)

**Comment by dansup** [comment]
@faissaloo @trwnh Fixed in the latest commits!
