### ISSUE TITLE
Content enlarged

### ISSUE THREAD

**Issue by Grazouillis** [pixelfed/pixelfed#322]
It would be nice if we can have or choose (by settings) another visibility for timelines and picture focus in profiles, with pictures expanded to the ends of the navbar content. 
In fact, pictures are often too small for me.

**Timeline :** 

Normal (actual)
![small](https://framapic.org/uV1haIWrEwNi/v8KGbmgMYEyx.PNG) 

Enlarged (suggestion)
![enlarged](https://framapic.org/tf2iAZPznwiW/Ye8z7LAiXw9x.png) 

**Picture view :**

From this 
![small](https://framapic.org/nT8F2a6vSLrk/DYW9ItSNCOic.PNG) 

to this 
![enlarge](https://framapic.org/zly6Acd9b24o/mLMFWeA3FA9n.PNG) 

=> Dirty method  :roll_eyes:  :
```
<div class="container p-0">
<div class="col-md-12 col-lg-12 mx-auto pt-4 px-0">
```

What do you think about it ?
... it's not quite like instagram, but maybe is it better for #accessibility ? My eyes become old !
#enhancement.

**Comment by eckad158** [comment]
i think a zoom / enlarge button would be nice.
maybe as an image overlay when hovered with mouse

**Comment by faissaloo** [comment]
I disagree that this should be an option, I see no reason to keep the current image size as it's quite impractical on a desktop and providing the option gives the opportunity for indecision on the part of users (unless this would be an instance setting rather than a user setting). That said I disagree that comments should be placed under the image on desktop.

**Comment by Grazouillis** [comment]
It's the reason why I suggest "_choose_ another visibility" (which can be activated or not !) in settings @faissaloo

**Comment by trwnh** [comment]
Might be better handled by #159. Currently, zooming in your browser should handle the "make everything bigger" use case.
