### ISSUE TITLE
Feed planning

### ISSUE THREAD

**Issue by thibaultamartin** [pixelfed/pixelfed#329]
Whether it is individuals or companies, there seems to be a need on Instagram for "feed planning".

Feed planning consist of a view where you organize your pictures as you intendend it to appear on your feed, without actually publishing it. It may be used to have a color-consistant feed, or determine what's the most pleasant to the eye. When done, the planner allows to remove everything from the feed and publish the pictures as designed.

Several apps address this need for Instagram. If PixelFed handled it natively it would be competitive as compared to Instagram.

**Comment by faissaloo** [comment]
I think this would be critical in getting the big guns on this platform

**Comment by dansup** [comment]
I started working on this feature in June, https://mastodon.social/@dansup/100411428146894516

**Comment by trwnh** [comment]
I think this is a bit of an anti-pattern if taken at face-value, e.g. creating 9 posts just for the profile view is not a good thing because it's just going to spam the feeds of people with 9 posts in a row that don't even show the full picture. The reason people do multiposts on Instagram is because Instagram is a closed platform and people are looking to replicate functionality that already exists in the open platform of the web.

What might be possible instead is to support draft posts that can be pushed live at a later date, either manually or on a schedule.
