### ISSUE TITLE
Unable to locate Mix file: /css/app.css. (View: /home/wwwroot/pixelfed/resources/views/layouts/spa.blade.php) 

### ISSUE THREAD

**Issue by zealov** [pixelfed/pixelfed#3526]
Unable to locate Mix file: /css/app.css. (View: /home/wwwroot/pixelfed/resources/views/layouts/spa.blade.php)

**Comment by mattsches** [comment]
Same thing happens to me, too, after having compiled the assets manually.

Turns out `.sass('resources/assets/sass/spa.scss', 'public/css')` is missing in `webpack.mix.js`, and after you add it, the error is gone … 
but now you get 

```
Unable to locate Mix file: /js/spa.js. (View: /var/www/html/resources/views/layouts/spa.blade.php) 
```

because the `spa.js` is also missing from the Webpack config. However, the file `spa.js` does not even exist :(

**Comment by zealov** [comment]
> 
me to

**Comment by zealov** [comment]
> 在手动汇编之后，我也发生了同样的事情。
> 
> 原来`.sass('resources/assets/sass/spa.scss', 'public/css')`失踪了`webpack.mix.js`，添加后，错误消失了…… 但你现在得到了
> 
> ```
> Unable to locate Mix file: /js/spa.js. (View: /var/www/html/resources/views/layouts/spa.blade.php) 
> ```
> 
> 因为 Webpack`spa.js`配置中也救援不存在。但是，该甚至文件`spa.js`不存在:(

应该是作者没有上传这两个文件导致的

**Comment by duck2b** [comment]
> > 在手动汇编之后，我也发生了同样的事情。
> > 原来`.sass('resources/assets/sass/spa.scss', 'public/css')`失踪了`webpack.mix.js`，添加后，错误消失了…… 但你现在得到了
> > ```
> > Unable to locate Mix file: /js/spa.js. (View: /var/www/html/resources/views/layouts/spa.blade.php) 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 因为 Webpack`spa.js`配置中也救援不存在。但是，该甚至文件`spa.js`不存在:(
> 
> 应该是作者没有上传这两个文件导致的


我也遇到同样的问题，现在有解决方案么？
