### ISSUE TITLE
Empty user profile 

### ISSUE THREAD

**Issue by twisterrm** [pixelfed/pixelfed#3549]
Hi,
When i click on a user profile (even on my profile), the result page is empty, unless i refresh the page
Looking at the logs the first request was completely ignored.
Docker installation with last commit

**Comment by mattsches** [comment]
I experienced the same thing.

It looks like an XMLHttpRequest to `/api/v1/accounts/relationships?id[]=1234567890` fails with a `500 Internal Server Error`, and as a result the page stops loading. However, I haven't had time to take a closer look yet.

I'm not sure why this calls the APIv1 endpoint anyway since it's the frontend and not an external client. In my case, it probably fails because I've set `OAUTH_ENABLED=false`. Maybe the route for this  call is wrong and should use the `web` route instead of the `api` route? I'm pretty new to the code, so: Can anyone explain this?

**Comment by mattsches** [comment]
I think I've found a wrong path in `public/js/profile-ojtjadoml.js`: it calls `/api/v1/accounts/relationships?id[]=1234567890` when it should call `/api/pixelfed/v1/accounts/relationships?id[]=1234567890`. I cannot explain why this is the case because the corresponding line in the `Profile.vue` component was last changed in 2019?

But I recompiled the JS assets, and now the wrong request path is gone, and the profile page seems to work fine.

What is the recommended way to fix this? Create a PR with all recompiled assets seems kind of wrong ...

**Comment by ghost** [comment]
Can confirm that I'm having the same issue too. I spun up a new Pixelfed instance from the [latest dev commit](https://github.com/pixelfed/pixelfed/commit/a2082367a1e1eaa9455a822c2f40716db98787eb) and the same issue persists.

**Comment by MrAn0nym** [comment]
> What is the recommended way to fix this? Create a PR with all recompiled assets seems kind of wrong ...

one of the maintainers is supposed to compile it

**Comment by dansup** [comment]
@twisterrm @mattsches @0xv31an5a1i5 You need to run `php artisan passport:install`, that generates the appropriate oauth keys for the apis.
