### ISSUE TITLE
Pixelfed profile incomplete when viewed from Mastodon instance

### ISSUE THREAD

**Issue by PCPandaStyle** [pixelfed/pixelfed#3609]
When I looked at my pixelfed.social profile from inside two different mastodon instances, I noticed that only a fraction of my posts are visible there.
One instance showed about 10% of my posts, the other one showed even less. And it was NOT only the latest posts, it was sort of random. The only pattern I found was that all posts were rather "popular", they all had shares and comments, and most of them had a lot of likes.
I tested this with some other Pixelfed accounts as well, with varying results. Some profiles were missing a lot of posts as well, some only missed a few, some seemed to be without any missing posts.
I already created a bug report for this on the mastodon page, since I don't know on which side the issue lies. Here's a link to it.
https://github.com/mastodon/mastodon/issues/18939

**Comment by MrAn0nym** [comment]
Afaik that's a normal federation problem
The mastodon instance doesn't know about the post as it was never specifically informed about it. The posts that were shown have probably been boosted by users of the mastodon instance

If an account on the mastodon instance follows your pixelfed account it should show all post from this point onward
(you can force fetch posts by searching for the post link in your mastodon instance)

One thing you'll also have to look out for when reconfirming the issue is that the posts may show up in another order

**Comment by PCPandaStyle** [comment]
OK, I understand that one instance can't always contact every other instance for every post.
But shouldn't for example mastodon check what it "missed" in that specific profile, once someone looks at the profile?

Force fetching seems to work, but it's not a practical solution to the problem.
