### ISSUE TITLE
Preserve alphanumeric order of multiple uploaded photos

### ISSUE THREAD

**Issue by ho1ger** [pixelfed/pixelfed#3708]
When you upload more than one photo to pixelfed, the order of how the photos are later displayed is -- as far as I can see -- random. It would be way better to order the photos using their file names, i.e. in alphanumeric order.

**Comment by SunDancerGE** [comment]
I second that vote. Either let the names of the files take care of sorting or add the ability to sort them manually.

**Comment by ungive** [comment]
> It would be way better to order the photos using their file names

I think they should be ordered the way they come in in JavaScript (or however uploaded files are handled). In my file picker (KDE on Linux) I can select them in the order I want. In [this demo](https://davidwalsh.name/demo/multiple-file-upload.php) I can provoke a different order in the output by selecting them in a different order, albeit they are shown in reverse order than the one I selected them in (not sure why). Sorting them lexicographically afterwards would be the same as randomising them to me.

If that's not possible an option to sort them manually would be greatly appreciated! Otherwise you have to sit there and upload each one manually and wait for each upload inbetween.

**Comment by jim-easterbrook** [comment]
I've been experimenting with repeatedly uploading the same four pictures (same file names!) and have been getting different display orders. The http request has them in the correct order each time, so it's not something in my program. (I can use arbitrary text as the "file name", so if that was used for sorting I could live with it.)

**Comment by jim-easterbrook** [comment]
Having written that I now can't make it go wrong again.

**Comment by stevenroose** [comment]
I think https://github.com/pixelfed/pixelfed/issues/798 is strictly better than this issue, though if it's an easy implementation, it would help the power user and be a nice extra :)

**Comment by jim-easterbrook** [comment]
Using the API I've been examining some of my posts where the pictures are displayed in the wrong order. Media ids are allocated sequentially and show the order in which my pictures were uploaded, but this is not the order in which they are being displayed. For example, my post id 531831456835812084 (https://pixelfed.de/i/web/post/531831456835812084) displays the media ids in this order: 2128655 2128559 2128597 2128620. The first one should be displayed last.
