### ISSUE TITLE
[Feature request] Make "Discover" page public

### ISSUE THREAD

**Issue by KaKi87** [pixelfed/pixelfed#3851]
As per :
> [Would rather have the discover page public](https://github.com/pixelfed/pixelfed/issues/214#issuecomment-435637917)
— @dansup

Thanks

**Comment by Peter65535** [comment]
Hi, fourthing (fifthing, maybe?) this request, as it is the one and only reason I'm not already running a pixelfed instance. 

Discoverability remains an enormous issue, and precisely zero people that don't already know what is on the site are going to be willing to blindly sign up to see if it's for them if they can't get some kind of idea what the community around the site is like. Additionally, noone is going to join up, because they fear that noone will ever see their posts, which unfortunately, seems to be mostly true with no ability to make the timeline public.

**Comment by mitexleo** [comment]
You can make the page public by setting a env variable in .env . There should be a menu in the Landing Page @dansup 

Checkout : https://nixorigin.one/discover
