### ISSUE TITLE
Propagation of post likes from Mastodon stopped working

### ISSUE THREAD

**Issue by uk3** [pixelfed/pixelfed#4012]
Hello,

I did not have the time to do a detailed check yet, but I just noted that somewhen between commit 434f1f229c0ea98f572e86bd373c5c090adfbea6 and the current head the propagation of post likes from Mastodon -> my Pixelfed stopped working. Likes are not shown any more (boosts still work and are shown at the post).

A like that came from a friendica installation worked

No Idea whats going on in detail so consider this an initial report - maybe someone else noted it.

Reverting to the mentioned commit fixed the issue it seems.

Greetings, Ulrich

**Comment by okpierre** [comment]
@uk3 likes from pixelfed instances seem to be working but nothing from mastodon instances

**Comment by HaraldWalker** [comment]
Same here since updating to latest on December 24th.

**Comment by snapai** [comment]
Same, I've observed this from my self-hosted instance (@ snapai @ pix.weanimatethings.com) and on the pixelfed.social instance, since the Dec 25th update.
Additionally, comments and boosts are not coming over from Mastodon.

I attempted to send a like and a comment to https://pixelfed.social/p/ScruffyDux/511796237524574512 from @ snapai @ dragon.style (Mastodon 3.4.6), neither appeared on the post.

Testing against one of my own posts on my single-user Pixelfed instance, Horizon shows the InboxValidator event fire, with the appropriate data for a like, boost, or comment, but that's it, it never appears on the post.

Liking my own work from within Pixelfed works as expected, as does liking a post on another Pixelfed instance from within mine (it shows up when the post is reloaded on the remote instance)

**Comment by jemayer** [comment]
@snapai Good to find this. I observe the exact same behaviour (including the Horizon events) and was debugging for hours to figure out if I made some dumb mistake when setting up my instance a few days ago.

**Comment by raphgilles** [comment]
Same on .fr !

**Comment by raphgilles** [comment]
And it's the same with followers count.

**Comment by jemayer** [comment]
> And it's the same with followers count.

Ha, I just was about to ask if that's something related, or only me experiencing.

**Comment by jemayer** [comment]
<img width="573" alt="Screenshot 2022-12-29 at 12 50 37" src="https://user-images.githubusercontent.com/2098403/209947281-6011ad52-6b0a-4953-bccc-ba661c4d333d.png">

JFYI. <3 I would love to know whether there is a way to repair the wrong status counts (or, as I also encountered, missing comments) which seem to have mostly been correctly fired through Horizon.

**Comment by okpierre** [comment]
@jemayer remote comments (with mastodon and other projects) and remote replies have been a problem for some time. Possibly as long as I've been testing and reporting bugs for pixelfed. I'll test with latest release soon and open a separate issue if this is still the case
