### ISSUE TITLE
[Question] do actions such as archiving, deleting, etc carry over to other services such as Mastodon? 

### ISSUE THREAD

**Issue by Outlet2048** [pixelfed/pixelfed#4332]
When I delete or archive a post on my account, does that action carry over to other instances of pixelfed? To other activity pub services?
Same for other activities such as making posts private or public after posting by changing your profile settings

**Comment by mitexleo** [comment]
Yes, if you delete a post it will be removed from  other instances as well. But it might not happen instantly as federation takes some time.

**Comment by dansup** [comment]
When you delete a post, it will trigger a federated activity that is delivered to remote instances your followers are on.

When you archive a post, it basically hides the post locally and doesn't remove it from remote instances.

**Comment by Outlet2048** [comment]
> When you delete a post, it will trigger a federated activity that is delivered to remote instances your followers are on.
> 
> When you archive a post, it basically hides the post locally and doesn't remove it from remote instances.

Thanks
Would it not possible to trigger a federated activity for that as well?
Or is archiving not supported on other platforms outside of pixelfed?

**Comment by trwnh** [comment]
there's no protocol support for "archiving" because currently, everyone just uses `Create`. in order to support "archiving", one would need to have implementations support the concept of "profiles as collections", where you can `Add` and `Remove` posts from a given collection (representing the "profile"), instead of dealing only with `Create` being delivered directly or fetched from `outbox`.
