### ISSUE TITLE
When trying to run docker-compose: docker manifest for pixelfed/pixelfed:latest not found

### ISSUE THREAD

**Issue by lullis** [pixelfed/pixelfed#4372]
I've tried all sorts of different tags: based on branch names, tag names... none of them worked.

What would be the right way to pull/build image?

**Comment by SteveDinn** [comment]
I'm currently using "quay.io/zknt/pixelfed"

https://quay.io/repository/zknt/pixelfed

**Comment by lullis** [comment]
Yeah, that's the one I was using as well. The problem is that I couldn't get it to work with S3 storage on docker swarm. I was hoping I could figure out the issue by starting from the source.

Is the docker deployment story such low-priority for the devs?

**Comment by lordkitsuna** [comment]
this seems to be a common issue with all open source media platforms atm. be it mastodon, lemmy, pixelfed. none of them have working documentation. (tons of the links for pixelfed 404 on the documentation page such as for config options,) are wildly outdated, and generally just dont work. docker also seems to always exist but be horribly broken. not sure why devs of these projects seem so uninteresting in people actually using the software but its really sad to see. the huge closed source sites have all been pushing users away but when they come to look at the alternatives they just see broken unusable systems and give up and go back to the closed source sites because at least they work. /rant
