### ISSUE TITLE
Instagram import confusing - does not update total number of posts

### ISSUE THREAD

**Issue by andypiper** [pixelfed/pixelfed#4475]
I've just (I *think*) imported the maximum 1000 posts from my JSON Instagram archive.

It's a little hard to confirm, because:

- the Import settings page now says I'm not allowed to use the feature due to hitting a limit, but, the import progress is no longer being shown (previously, it would show the number of queued items, and the number of imported items)
- my account Profile shows a total of 50 posts, which may (or may not) be the number that I had previously posted directly to Pixelfed, prior to the import... I think that's the case, based on a quick count down the page and my memory of what I'd posted directly vs what was imported.

Is this expected behaviour, and will the total number of posts eventually reconcile with the import progress?

**Comment by madranet** [comment]
Blimey! --how on earth did you manage to import 1000+ posts.

I just came here to see if anyone was mentioning the fact that --annoyingly!-- you have to click each individual post you want to import from Instagram, rather than being able to 'Select All'.  And I thought it was a pain in the nethers, with my sub-100 posts to import!

Don't get me wrong. I'm glad to see Instagram import is here [at last!].  But, after waiting 4 years...

I refer the honourable readers to the issue I raised, some time ago ---> https://github.com/pixelfed/pixelfed/issues/765

...I was hoping it would be a bit more user friendly

* No way to "select all" for import
* No kind of progress to know how it's going
* Confusing messages --a _"Don't close this window or navigate away"_ dialogue pops up after initiating th import. Then it disappears after a few seconds, leaving me staring at a "Processing Imported Posts" message on my settings page.  Er.... can I navigate away now? Or do I have to leave this settings page open until &lt;something&gt; happens?  Because it sure ain't giving me any further info, or any indication that *anything* is going on.

**Comment by madranet** [comment]
Sorry. I'm double-posting here. But I've been following [a similar issue](https://github.com/pixelfed/pixelfed/issues/4473) and the same points seem relevant here:

As an experiment, I tried going through the import process again, on one of my imports that has been stuck on this for the best part of the day...

![SS 2023-06-13 at 16 57 08](https://github.com/pixelfed/pixelfed/assets/669658/78deac36-dba4-4138-b999-5f10b7627414)

I re-uploaded the JSON.zip file and got the following...

![SS 2023-06-13 at 20 54 28](https://github.com/pixelfed/pixelfed/assets/669658/ac20047d-1857-47b6-baed-f437c3e3ab3f)

So, again, I'm calling 'unhelpful UI' on this one. Is the import dialogue completely broken here?... or is it not showing me anything to import because all the posts contained in that JSON.zip file are already queued for import from my earlier attempt? --albeit in a queue that doesn't seem to be moving.

If the latter, then a message saying  something like _"All available posts are already queued for import"_ might have helped!

**Comment by madranet** [comment]
Well, this just keeps getting better and better!

I've just revisited the two imports which I left "eternally queued" yesterday and....

. One [with 93 posts] has just vanished entirely:

![SS 2023-06-14 at 12 44 41](https://github.com/pixelfed/pixelfed/assets/669658/d0cc7f5a-7108-4860-8b02-0ef38e133f0c)

. The other [with 74 posts] has imported 9 of them and the rest have vanished:

![SS 2023-06-14 at 12 42 56](https://github.com/pixelfed/pixelfed/assets/669658/1595ddbb-2c8e-4ef8-9eca-229da6991397)

No messages, no progress reports, no explanations.

Just for "Da LULZ" [as the kids would say, I tried doing one of the imports yet again. This time a new variation. Import dialogue shows all the posts with no content:

![SS 2023-06-14 at 12 54 23](https://github.com/pixelfed/pixelfed/assets/669658/0c91eba0-40ec-45c9-886c-6ec6c59cefaa)

Was this import feature even tested before it was pushed out the door [with such hyperbolic fanfare](https://pixelfed.blog/p/2023/feature/introducing-import-from-instagram)? I can't remember the last time I saw a new feature release fail in so many ways at once.

![SS 2023-06-14 at 12 50 42](https://github.com/pixelfed/pixelfed/assets/669658/cf14710c-deb8-4b88-ab45-a066196d00cc)

**Comment by daSmirnov** [comment]
So I'm running in Docker, performed the import approx  18 hours ago now.  Was stuck on importing since then.

Ran `docker-compose exec app php artisan schedule:run` which has processed the import.

But now seeing same UI issue as above 
![image](https://github.com/pixelfed/pixelfed/assets/79381387/1f8b8dce-d0b6-4b08-90cf-bb6012555227)

Posts show up in my profile all blank with no media.  I've got two other test instances which are now running the same build, so will test those this evening without leaving as much time before running the schedule:run.

### UPDATE.

For the benefit of everyone else, checked permissions of those images and they weren't owned by www-data, of course since I ran the command as myself!  Changed ownership to www-data and now works properly!

**Comment by madranet** [comment]
> For the benefit of everyone else, checked permissions of those images and they weren't owned by www-data...

Just to re-iterate; I'm running into these issues trying to import some Instagram accounts into the primary Pixelfed  instance at [pixelfed.social](https://pixelfed.social). I think it's worth mentioning again because I know some people running local instances will be scratching their heads, thinking they've messed up their install somehow.  My experience suggests that the import feature itself is broken, not necessarily anyone's individual installation.

**Comment by madranet** [comment]
More on previous:

I've just checked the source on the blank import dialogue I showed above....

As you can see the image URL is completely blank. So it's not just an odd display issue:

![SS 2023-06-14 at 14 55 01](https://github.com/pixelfed/pixelfed/assets/669658/616d6924-b71a-4f9d-a8f6-9f8e79cf8536)

Just on the off-chance, I also checked the `JSON.zip` file I was trying to import, as someone else said that they reckoned maybe `webp` files didn't import and that was the problem. As you can see, my `JSON.zip` archive media files are all `.jpg`

![SS 2023-06-14 at 14 56 32](https://github.com/pixelfed/pixelfed/assets/669658/a00bfe2f-5f09-4fb6-9141-1e64d2b44787)

**Comment by SteveDinn** [comment]
Have you had a chance to check out the commit from today? It purports to fix this stalled import issue. In fact, I had done a test import into my account on pixelfed.social back when this feature was first announced, and it had stalled. But when I checked it today, all the photos are now on my profile.

My personal instance is a different story. Despite upgrading to the [latest commit on the main branch (as of this comment)](https://github.com/pixelfed/pixelfed/commit/da90bf630a3485a556a26e310219768906121520), my queue has not moved.

When I run `docker-compose exec app php artisan schedule:run`, I get `No scheduled commands are ready to run`. Is there some other way I can give the mechanism a whack to start processing again?

**Comment by ortizdr** [comment]
I have the exact same issue.

**Comment by andypiper** [comment]
Responding to my own original issue here:

> my account Profile shows a total of 50 posts, which may (or may not) be the number that I had previously posted directly to Pixelfed, prior to the import... I think that's the case, based on a quick count down the page and my memory of what I'd posted directly vs what was imported.

My account is now showing 1089 posts, which is much more likely to include the Instagram import! So I do not know what has changed, but this seems to have been fixed (on pixelfed.social).

I am not allowed to use the Import feature with this account any more, but that's presumably because I hit the limit of posts - the UI is unclear about this, it might be nicer if it was more specific.

For me this issue is resolved, so I'm going to close it, if others continue to see it maybe start an alternative thread here.
