### ISSUE TITLE
Some UTF characters are encoded/decoded wrongly during Instagram export/import

### ISSUE THREAD

**Issue by unsolaci** [pixelfed/pixelfed#4479]
I tend to use characters like "Σ" instead of "E", 'cause I'm edgy like that, "—" as separators, and sometimes emojis in my Instagram post descriptions. Quite a nasty mix.

Here's an example description from my [Instagram post](https://www.instagram.com/p/CVyPUAgAO88/):
```
I N F V S Σ
👩 @poziomczan_czekoladodylu
—
#light #red #pentagram #smoke #incense #ritual
#witch #polishwitch #witchy #witchyvibes #autumn #fall #halloween
#photoshoot #portrait #portraitphotography #model #femalemodel
```

Here's what it looks like in the exported JSON:
```json
"title": "I N F V S \u00ce\u00a3\n\u00f0\u009f\u0091\u00a9 @poziomczan_czekoladodylu\n\u00e2\u0080\u0094\n#light #red #pentagram #smoke #incense #ritual\n#witch #polishwitch #witchy #witchyvibes #autumn #fall #halloween\n#photoshoot #portrait #portraitphotography #model #femalemodel"
```

And here's the description in the imported [pixelfed.social post](https://pixelfed.social/p/unsolaci/1074896211102011):
```
I N F V S Î£ ð© @poziomczan_czekoladodylu â #light #red #pentagram #smoke #incense #ritual #witch #polishwitch #witchy #witchyvibes #autumn #fall #halloween #photoshoot #portrait #portraitphotography #model #femalemodel
```

This might not be Pixelfed's fault at all, and quite possibly due to the way these characters are encoded by Instagram in its post exports.

I'm not too sure what this encoding is exactly, but when I compare it with HTML entity tables it looks like Pixelfed is converting them correctly.

But why would Instagram convert these characters like that? Again, on IG website and app they all show correctly, so I might be missing something.

**Comment by realpixelcode** [comment]
Perhaps related to issue #1847 (wrongly closed) which also occurs outside the context of Instagram imports.

**Comment by xavsworld** [comment]
It's seems to be a problem from IG's JSON data. I do have the same issue, after importing my own IG stuff. Since I do use French and English on my post descriptions, some chars are simply mess-up. Thats being said, the issue occurs even if you have no emojis.

While trying to research on the issue, in order to help for describing the issue, I do think I've figured out the problem is the following. IG encode the the hex value of the character using the \u escape char, prefixed with two zeros. However, we must use the Unicode Code Point, who is totally a different thing! (I've learned something today)

In PHP, you can use the hex using the \x escape sequence, then followed by 2 hex decimals (example: "\x61" will print the lowercase letter a). But we can’t do this in a JSON string.

#### Example
The Sigma Symbol (Σ) from @unsolaci example is encoded using \u00ce\u00a3. If we replace the "\u00"s with "\x", we end up with "\xce\xa3". If we run this in the PHP interpreter, we have, surprise surprise, the sigma symbol.
```
~ php -a
Interactive shell

php > echo "\xce\xa3";
Σ
php >
```
Ok, great. But, we do need to convert this to UTF so we can easily show that to users. Thats why we do need to convert it to unicode code point values, so we can really use this as an escaped \u, who is supported a bit more universally.

I've found thru the research I did we can use the json_encode function to get that unicode code point. If we do remove the quotes who wrap the value, we got the correct utf code-point.

```
~ php -a
Interactive shell

php > echo substr( json_encode("\xce\xa3"), 1, -1 );
\u03a3
php > echo "\u{03a3}";
Σ
php >
```
Then, just to double-check, we can look-up on any [UTF-8 character map site](https://symbl.cc/en/03A3/). 
<img height="475" alt="validation-check" src="https://github.com/pixelfed/pixelfed/assets/178318/29a93874-82a4-477f-ade4-98d0312f6aa9">

Here is an other test with the woman emoji.
```
~ php -a
Interactive shell

php > $original_str = '\\u00f0\\u009f\\u0091\\u00a9';
php > $hex_str = str_replace('\\u00', '\x', $original_str );
php > echo $hex_str;
\xf0\x9f\x91\xa9
php > echo '\xf0\x9f\x91\xa9';
\xf0\x9f\x91\xa9
php > echo "\xf0\x9f\x91\xa9";
👩
php > echo substr( json_encode("\xf0\x9f\x91\xa9"), 1, -1 );
\ud83d\udc69
php > echo "\u{d83d}\u{dc69}";
������
```
Ewww, this time, it's haven't worked. But, in a web browser, it's works apparently!
```
> "\ud83d\udc69"
< "👩"
```
It's something I'm discovering, and it's seems nobody speaks emojis the same way. If i push my research a bit more, the real Unicode code point for this emoji is [1F469](https://symbl.cc/en/1F469/). If we try that code into PHP's console, it's works.
```
~ php -a
Interactive shell

php > echo "\u{1F469}";
👩
```
But according to the ECMA-404 JSON standard, only 4 digits are allowed, and we can demonstrate it on the shell. 
```
~ php -a
Interactive shell

php > echo json_decode('"\u1F469"');
὆9
php
```

So, starting from my initial assumption, it's not a simple find and replace. 

To be fair, I pushed my research a bit more. I think I've found a solution. Here is a proof of concept:

```php
<?php

function fixIgUnicode($text) {

	// Convert bad unicode chars from IG's export
	$str = preg_replace_callback('|\\\\u00[0-9A-Fa-f]{2}|m', function($matches) {
		$newVal = str_replace('\\u00', '', $matches[0]);
		$clean_str = chr(hexdec($newVal));
		return $clean_str;
	}, $text);

	// Transform the unicode stuff to real emojis
	// based from: https://stackoverflow.com/a/71619308
    $str = preg_replace_callback(
        "%(?:\xF0[\x90-\xBF][\x80-\xBF]{2} | [\xF1-\xF3][\x80-\xBF]{3} | \xF4[\x80-\x8F][\x80-\xBF]{2})%xs",
        function($emoji){
            $emojiStr = mb_convert_encoding($emoji[0], 'UTF-32', 'UTF-8');
            return strtoupper(preg_replace('/^[0]+/','', IntlChar::chr( hexdec(bin2hex($emojiStr)) ) ));
        },
        $str
    );

	return $str;
}

$strs = array(
	"I N F V S \u00ce\u00a3\n\u00f0\u009f\u0091\u00a9 @poziomczan_czekoladodylu\n\u00e2\u0080\u0094\n#light #red #pentagram #smoke #incense #ritual\n#witch #polishwitch #witchy #witchyvibes #autumn #fall #halloween\n#photoshoot #portrait #portraitphotography #model #femalemode",
	">#\u00e2\u0082\u00ac|?\\\u00e2\u0082\u00ac|~>>\u00e2\u0082\u00ac{ Y NEIGE!!",
	'March\u00c3\u00a9 de No\u00c3\u00abl allemand de Qu\u00c3\u00a9bec'
);

foreach( $strs as $one_str ) {
	echo fixIgUnicode($one_str). "\n\n";
}
```
And the results are interesting:
```
~ php test.php
I N F V S Σ
👩 @poziomczan_czekoladodylu
—
#light #red #pentagram #smoke #incense #ritual
#witch #polishwitch #witchy #witchyvibes #autumn #fall #halloween
#photoshoot #portrait #portraitphotography #model #femalemode

>#€|?\€|~>>€{ Y NEIGE!!

Marché de Noël allemand de Québec

~
```
Thats being said, I have not enough sample to be able to run this on a large scale and test the results. I've just figured out I never used emoji's on my IG in the past. Only french accentuated chars. My sample is not enought wide to be able to be confident it's tested on enough stuff. 

And a silly question i'm asking mysef is if the problem is concentrated on export after a certain moment, where it's totally random, or let's say, on export of all users excepted some usernames. ;-) I guess this need more investigation. 

And again, I don't have much knowledge with Unicode. Feel free to bring a better solution! :) 

Hoping this will be helpful!

**Comment by Truhe2342** [comment]
I noticed that german umlauts and emojis are not imported correctly, therefore every imported post is broken.

**Comment by paulexyz** [comment]
@xavsworld is correct, issue beeing that the processing is not done by the php part of the application. The zip gets unpacked and the json parsed in the frontend in vue code. From there on only male formatted strings are passed onto the php and then into the database...

This means the fix or rather workaround needs to be implemented here: https://github.com/pixelfed/pixelfed/blob/dev/resources/assets/components/AccountImport.vue#L352C14-L352C14

I have a working semi working version but i can't recompile the assets since that's apparently broken atm #3434

**Comment by groovenectar** [comment]
Nice sleuthing @xavsworld

Here is another discussion about it: https://stackoverflow.com/a/50827817

It seems to be a common pattern in Facebook exported data, the `\u` must be misleading and apparently it's not actually Unicode? That discussion also suggests the use of regular expressions as part of a blanket solution

Your test case is very convincing already.

As far as I can tell the fix in the backend should go somewhere in this method: https://github.com/pixelfed/pixelfed/blob/dev/app/Http/Controllers/ImportPostController.php#L135

So your function becomes a private method in the class, then calling it e.g.:

`$ip->caption = $this->fixIgUnicode($ip->caption);`

**Comment by groovenectar** [comment]
It would be great to have a minimal test export `.zip` that can reproduce this issue if that would be possible to construct and post. Same with the umlauts

**Comment by groovenectar** [comment]
So I went to go create a test `.zip` myself and realized that at some point Instagram changed the export format from HTML to JSON. All I have is the HTML format version which I'm not sure even still exists.

This could be an ongoing issue of some kind, which leads me to believe that it would be worth a separation of concerns in some way. I am highly motivated to make this happen. I am not able to generate test cases myself because Instagram banned me along with _years_ worth of _time-consuming_ documenting and editing from my first media art gallery there.

One of the last archives I have from an Insta account has a directory structure like this:

![image](https://github.com/pixelfed/pixelfed/assets/595446/f5eeea5e-2ffa-49b9-a76a-2d4b17a432a9)

What I'm hoping is that there's a way for someone to empty out all their personal information from their archive of the newer JSON format except for images, then re-zip it for testing.

I'll clean any extra non-personal data myself if you'd like, just would really like to be able to put a test case together and help make sure imports are working perfectly for everyone.

**Comment by mattcen** [comment]
Here you go. The emoji at the end of this post should be a 💜 (https://emojipedia.org/purple-heart), and appears in the JSON as `\u00f0\u009f\u0092\u009c`, but gets rendered by PixelFed as `ð`
[mattpcen_20230923.zip](https://github.com/pixelfed/pixelfed/files/12707618/mattpcen_20230923.zip)

**Comment by groovenectar** [comment]
Perfect @mattcen 

Here's what I saw when I went to import:

![image](https://github.com/pixelfed/pixelfed/assets/595446/7fad1340-30a7-474a-a8ee-5c26b60ba33c)

And the final imported post: https://pix.dup.bz/i/web/post/1000001200312010

> This post description has emoji at the end of it ð

Going to need to make a way to do this...

The approach I think I want to take is to write something that will fix the archive itself, change the JSON and re-compress, in a separate script. Since I'm familiar with PHP, I think that would be the language I'd go with...

An issue is that the import takes place in JavaScript, so maybe I should use that.. But I still think it should be a separate script, then ported into Pixelfed

**Comment by mattcen** [comment]
I suspect plenty of folks will have this issue, and expecting them to do unpack and edit their archive before importing to Pixelfed is a big ask. Ideally this should be done in the JS frontend during the import, possibly with a checkbox to enable/disable the character substitution.

**Comment by groovenectar** [comment]
I agree, or maybe even without the checkbox (at first) ... reason being, it's already tagged as experimental ... and we know that emojis are common and the fix should be consistent .. I would say put and force the fix in, then fix any new cases around that in order to fine-tune the fix

I would imagine there are more cases than what is being reported too

**Comment by groovenectar** [comment]
We need to make sure the frontend can be compiled in this context, and someone reported that latest Git did not compile.

**Comment by paulexyz** [comment]
@groovenectar Yep i've tried to implement such a solution which does exactly that but since the frontend compiling is broken i can't really contribute to this project. i've fixed and error here and there to get it to compile - but e.g. icons are still broken. @dansup is this something you could look into so contribution from outsiders is possible again?

**Comment by paulexyz** [comment]
@xavsworld since a couple of weeks the frontend compiles successfully, i've took the time to implement a fix. Feel free to check out my PR #4726

You can just easily define the function in your local browser dev console and test it if you wanna verify it's functionality.
```
function fixFacebookEncoding(string) {
    const replaced = string.replace(/\\u00([a-f0-9]{2})/g, (x) => String.fromCharCode(parseInt(x.slice(2), 16)));
    const buffer = Array.from(replaced, (c) => c.charCodeAt(0));
    return new TextDecoder().decode(new Uint8Array(buffer));
}

> fixFacebookEncoding("\u00c5\u0099")
should return: 'ř'
```

For those who wanna just checkout a repo and run the project I've also committed a compiled frontend version on a different branch [insta-import-utf8](https://github.com/paulexyz/pixelfed/tree/compiled/insta-import-utf8) branch in my repo
