### ISSUE TITLE
Insta-import issues

### ISSUE THREAD

**Issue by mgrzeca** [pixelfed/pixelfed#4507]
Instagram import still has several major issues:

- It incorrectly imports emoticons.
- It incorrectly imports characters outside the US-ASCII character set.
- It doesn't preserve the order of imported posts from the same day, resulting in the sequence of posts losing its meaning, especially when they are related to an event or have cause-and-effect connections.
- The import process still encounters errors (see examples below), and it doesn't complete successfully.
- The imported posts are unlisted, which prevents interaction with these posts from other instances. In the case of a single-user personal instance, importing doesn't make sense unless it serves as a private archive of Instagram posts, as the imported posts are visible only to their author.

Example error messages:

[blad1.txt](https://github.com/pixelfed/pixelfed/files/11882749/blad1.txt)
[blad2.txt](https://github.com/pixelfed/pixelfed/files/11882750/blad2.txt)
[blad3.txt](https://github.com/pixelfed/pixelfed/files/11882751/blad3.txt)

**Comment by philsherry** [comment]
I just came to raise an issue about imported posts being unlisted, but not being able to change that status. 

When I looked through existing issues, I found this one which mentioned the unlisted problem. As such, I've tagged onto here for now.

@dansup, please shout if you want me to write this up as its own issue.

**Comment by sivy** [comment]
Just dropping here that imported posts being unlisted, and #823 showing that visibility cannot be edited, means that "hey hooray I moved from insta" but _no one can see my pictures_, _I can't use them for the Portfolio features_, and _I can't fix it_.

This is way no bueno. 😠

**Comment by glitchbirdnew** [comment]
Hey, I need your advice. After Instagram import, I can't see imported pictures on my profile. I asked the same question @dansup but I didn't get any replay from him so please if you guys have any advice, let me know. Please see the screenshot. 
![b5fa5e439d93b8d8](https://github.com/pixelfed/pixelfed/assets/109934632/5689e24f-e935-423b-937b-174ab545b40b)

**Comment by mgrzeca** [comment]
I had the same issue. The problem should be solved by executing the following command:

```
chown -R www-data:www-data /var/www/storage/app/public/m/_v2
```

Additionally, to avoid such issues in the future, the task scheduler 'php artisan schedule:run' should be run from the 'www-data' user.

Please note that the above user/group may vary depending on your environment/system and whether you are using php-fpm + nginx or mod_php + Apache.

**Comment by glitchbirdnew** [comment]
Hi, nothing changed. I am still having the same error: Error: The requested image could not be loaded.

here is my path chown -R www-data:www-data /home/pixelfed/storage/app/public/m/_v2

I followed https://docs.pixelfed.org/running-pixelfed/installation/

**Comment by lonestaritaly** [comment]
> Just dropping here that imported posts being unlisted, and #823 showing that visibility cannot be edited, means that "hey hooray I moved from insta" but _no one can see my pictures_, _I can't use them for the Portfolio features_, and _I can't fix it_.

Also it's not advised anywhere that the posts will be imported in this way. I wouldn't even have wasted the time to export from Instagram and then import if I knew in advance that the posts would have been only for my personal view and for those who should come and see my profile on my instance.

if this is by design, it should be clearly stated in the import web page.

**Comment by paulexyz** [comment]
@sivy the visibility seems to be a feature which shall not be able to be edited by an end user since it's part of the moderation tools for administrators. Yes the default might not be set appropriately. Line reference and screenshot are attached here https://github.com/pixelfed/pixelfed/issues/4610#issuecomment-1789823108

**Comment by paulexyz** [comment]
@mgrzeca most of the issues you encountered shall be fixed if you fix the parsing of the broken Facebook JSON encoding. That also prevents having garbage in the import queue which fixes some of the errors you encountered. I've created a PR for fixing that #4726.
That also fixes some of the issues  @glitchbirdnew had with the missing previews because the js code does not explode anymore
