### ISSUE TITLE
Deleted account shown in mastodon instances

### ISSUE THREAD

**Issue by anxiouslelimo** [pixelfed/pixelfed#4520]
Previously deleted accounts from pixelfed.social still searchable and shown in mastodon instances. Even edited or deleted posts are shown in profile.

**Comment by trwnh** [comment]
there's no way to send a Delete to everyone who has a copy of a profile or post, because anyone can fetch posts at any time without authentication. deletion across the fediverse is a best-effort thing, unfortunately. you could send Deletes to every single server you know about and you'd still miss some.
