### ISSUE TITLE
Can't add imported Instagram image into a Collection

### ISSUE THREAD

**Issue by jfmartin67** [pixelfed/pixelfed#4610]
Adding a photo to a collection coming from an import of Instagram into Pixelfed, we get an Invalid URL error.

**Comment by paulexyz** [comment]
This has probably to do with the fact that all imported posts are set to the have the default visibility set to `unlisted`.  Changing is not possible by a user. That's probably due to the fact that this is "status" is a moderation feature used only for/by admins as you can see in the following screenshot. #4506 has a related discussion
![image](https://github.com/pixelfed/pixelfed/assets/25357870/3c62289c-f4d4-41b9-8153-e71d362f3a7f)

Why that might be the case i don't know - but here is the line of code which causes this...
https://github.com/pixelfed/pixelfed/blob/4b9d0dc6efb1206ac51fc00e6f94c264da33d278/app/Console/Commands/TransformImports.php#L104-L105

**Comment by bergie** [comment]
This seems very confusing to new users, especially ones migrating from Instagram. The way it’s currently done, the Instagram-imported images are invisible for authenticated users (and followers of the account), but _are_ visible when you’re visiting the account page without being logged in. That would seem to be the completely wrong way around for what I would imagine “unlisted” to mean.

Authenticated:
![IMG_1123](https://github.com/pixelfed/pixelfed/assets/3346/63ba9414-cec5-453c-8e64-d2a3811cc752)

Unauthenticated:
![IMG_1124](https://github.com/pixelfed/pixelfed/assets/3346/fc35ebf0-e57b-4318-88e4-09c6d5f5f72d)

And of course it is weird that users themselves can’t change the visibility (#4506)
