### ISSUE TITLE
Instagram Import - UTF8 text problem

### ISSUE THREAD

**Issue by imto1** [pixelfed/pixelfed#4638]
Posts with Persian/Arabic text imported incorrectly and all texts displayed as ASCII chars.
My account is on [pixelfed.social](https://pixelfed.social) instance.

![Screenshot from 2023-09-06 10-20-31](https://github.com/pixelfed/pixelfed/assets/43239919/6ebd546f-c72d-4a8c-a009-c71ccf147433)

**Comment by unsolaci** [comment]
This is probably related to #4479

**Comment by groovenectar** [comment]
Is there any chance you could prepare a minimal example to debug this? E.g., unzip the export, delete everything except the post that doesn't import properly, re-zip and post the zip file for debugging and testing?

**Comment by imto1** [comment]
> Is there any chance you could prepare a minimal example to debug this? E.g., unzip the export, delete everything except the post that doesn't import properly, re-zip and post the zip file for debugging and testing?

OK. I will attach the file when it's ready.

**Comment by groovenectar** [comment]
> OK. I will attach the file when it's ready.

No worries! Someone was already kind enough to make this effort in this thread: https://github.com/pixelfed/pixelfed/issues/4479

Don't do it for now! Sorry for not updating this thread sooner

**Comment by instalution** [comment]
Idea for standard import format! This would allow:

1) PixelFed to focus on PixelFed while import concerns are separated.

2) A standalone program with Composer library so PixelFed can use the imports directly.

3) Some additional recognition for Pixelfed since development could happen under the Pixelfed umbrella, yet the standard format can be used by all Fediverse applications. I'm willing to get started on a repository for this idea if @dansup might eventually agree with the outlined vision and have time to set aside for it.

4) An offset for any potential future quirks with imports that might arise.

For the format, we could use ActivityPub format itself!

Say you have a folder of images:

![image](https://github.com/pixelfed/pixelfed/assets/108841276/0dffa438-bc1b-4cad-994e-0464f5f3f6ca)

There could be an `.activitypub.json` file in each directory that defines the metadata for each media file. This way, specific Fediverse flavors could include their own special metadata optionally and follow ActivityPub specification. Then the whole folder is zipped and named e.g. `myimportfiles.aparchive` (for "ActivityPub Archive") or some other file extension. People can still optionally upload a direct Instagram import, which can be detected (thanks @mattcen for the [minimal export example](https://github.com/pixelfed/pixelfed/issues/4479#issuecomment-1732458435)). PixelFed can use the library and the library would be responsible for ensuring that the import is parsed.
