### ISSUE TITLE
Login with Mastodon broken

### ISSUE THREAD

**Issue by pablo03v** [pixelfed/pixelfed#4681]
Since the "sign in with Mastodon" feature was introduced it didn't work for me.

I'm trying to register using tech.lgbt but I always get an error message saying that the server isn't compatible. I don't get if this is an issue from the server side and if so what I need to tell my admins to make it work or if this is a limitation of pixelfed only letting some servers do this.
![76b93012-90a6-4afd-9b7b-0cab71f8cdd0](https://github.com/pixelfed/pixelfed/assets/93644977/6b012e9b-faa4-4e3f-be87-6a442bb11d48)

**Comment by dansup** [comment]
It appears tech.lgbt is blocking FediDB which is used for this feature, it may work on instances who do not have max uses enabled.

**Comment by pablo03v** [comment]
aha, so it is indeed tech.lgbt and not Pixelfed which bugs me. Well, thanks for looking into this Daniel! 💙

**Comment by D1reW0lf** [comment]
Apologies for resurrecting this thread but since I'm having the same issue I thought that it's better to keep it all on the same discussion. 

When someone tries to use our mastodon instance, social.thewhole.site, they cannot log in with that exact error. 
In the federation area of Mastodon, I can "see" our Pixelfed there, so I really don't know what might be happening. 

Any help is more than welcome.

Thank you!

————
Edit:

When I tried to add either kinkpic.site or social.thewhole.site to FediDB on both situations it gets stuck on "We found your instance, please wait..."

![IMG_1486](https://github.com/pixelfed/pixelfed/assets/1677707/967756c6-33bd-4034-951d-2c3adcf23220)

**Comment by ShadowJonathan** [comment]
> It appears tech.lgbt is blocking FediDB which is used for this feature, it may work on instances who do not have max uses enabled.

@dansup this is no longer the case, and fedidb doesnt appear to update all fields (as we have since switched to `@mods` instead of `@david` for our administration account), and it is still broken.

**Comment by zeroesca** [comment]
This just started happening to zeroes.ca on Jan 23rd. We've been using mastodon sign-in with pix.zeroes.ca for quite a while without issue. We migrated Pixelfed to a new server and ip on Jan 11/12, but had not been having any trouble signing in until Thursday. The listing for zeroes.ca on fedidb is a few days out of date at least, not sure if that could be contributing. There are other apps on the same server and ip as pix.zeroes.ca that oauth against the zeroes.ca mastodon server and I've not been able to identify any other connectivity issue between the two boxes.
