### ISSUE TITLE
Like / Favorite / Heart "not sticking"

### ISSUE THREAD

**Issue by RiversideBryan** [pixelfed/pixelfed#4723]
Action does't remain when clicking like on another user's post (like in the mobile ui or the hearts in the pixelfed app for Android).
When scrolling past the same post again, the like has disappeared.  
When leaving the screen to another page, and later viewing that post again, the like has disappeared.

**Comment by dansup** [comment]
@RiversideBryan This is due to the way we process likes, I moved it into a new `feed` job queue which should process them faster. 

Previously, they were dispatched to the default job queue which could be backlogged and sometimes take several minutes to process, by moving them to a new `feed` queue this should help the "stickyness" problem until we implement the long term fix (by refactoring the like cache)
