### ISSUE TITLE
API /api/pixelfed/v1 get 403 error

### ISSUE THREAD

**Issue by SmartAssistent** [pixelfed/pixelfed#4885]
I write my own mobile app. When I call /api/pixelfed/v1/*, I get a 403 error, but if I call /api/v1/*? all is good.

I need to call /api/pixelfed/v1/timelines/home because it has the same result as /api/v1/timelines/home, and does not have options:
liked_by
comments_disabled
reply_count

I think this happened because the mobile app does not have Cookie 'laravel_token'

**Comment by dansup** [comment]
This is intentional, `/api/pixelfed/*` is reserved for the web apis.

You may want to try adding `?_pe=1` to your home timeline requests to return the Pixelfed Entities which include `liked_by`, `comments_disabled` and `reply_count` without having to try and bypass cookies to access the web ui.

Example: `https://pixelfed.social/api/v1/timelines/home?_pe=1`
