### ISSUE TITLE
Uploading .heif files stopped working after 2023/02/15 6:26 UTC+2

### ISSUE THREAD

**Issue by zipkid** [pixelfed/pixelfed#4947]
My last post, via the Pixelfed IOS app, https://pixelfed.social/i/web/post/663795448490505957, was from a .heif image.
Now i get an error that only jpeg, png, or mp4 are allowed. The Web UI also limits to these files in the upload dialog.

**Comment by philiprenich** [comment]
@trwnh ~~can you comment on why this stopped working? I noticed you’ve closed a few comments asking about .heic /.heif files as “not planned” but made no comment around it.~~

~~It used to work, so what’s changed that it is no longer supported? Was there a change on Apple’s end or was code removed/altered here or a dependency making it too hard to support?~~

Edit: Playing around a bit more, if I select the options menu on the iOS photo selection sheet and say Large instead of the original file size I can upload (and I’m assuming iOS converts to jpg prior to upload). I’m investigating why this is still as my server says it supports very large files and the original is only 3.5mb or so.
