### ISSUE TITLE
Docker: unable to startup `Waiting on lock /var/www/storage/docker/lock/entrypoint.sh`

### ISSUE THREAD

**Issue by jamespanic** [pixelfed/pixelfed#5004]
Continuing from #5003 … i disabled the depends lines for web and worker but my web container won't start up. It shows

`Waiting on lock /var/www/storage/docker/lock/entrypoint.sh`

I have `DOCKER_APP_ENSURE_OWNERSHIP_PATHS="/var/www/storage /var/www/bootstrap/cache"` in `.env`.

That file does get created but it's empty.

**Comment by jamespanic** [comment]
@jippi Any thoughts on this?

**Comment by ricardo-maestas** [comment]
@jamespanic is a new pixelfed instance or is this happening with an instance you're [migrating to Docker v2](https://jippi.github.io/pixelfed-docs-next/pr-preview/pr-1/running-pixelfed/docker/migrate/v2.0.html)?

**Comment by jamespanic** [comment]
@ricardo-maestas This is on an old instance I'm trying to upgrade to the new docker style.

**Comment by ricardo-maestas** [comment]
Check the logs of the various containers, in particular the DB container since others depend on it to start. In my case when I used the db image that came with the default compose file it caused issues.

**Comment by jamespanic** [comment]
This is the root cause of my problem

https://github.com/pixelfed/pixelfed/issues/5023

**Comment by jippi** [comment]
Sorry for not following up here - I've mostly given up finding a way to continue contributing to Pixelfed Docker, as I [have 4 fixes pending for a month or so now](https://github.com/pixelfed/pixelfed/pulls/jippi) with no real path or responsiveness from the maintainers. 

My request for becoming maintainer of it has also yielded nothing, despite being present in the [CODEOWNERS file](https://github.com/pixelfed/pixelfed/blob/dev/CODEOWNERS) since my original PR was merged in

**Comment by dansup** [comment]
> Sorry for not following up here - I've mostly given up finding a way to continue contributing to Pixelfed Docker, as I [have 4 fixes pending for a month or so now](https://github.com/pixelfed/pixelfed/pulls/jippi) with no real path or responsiveness from the maintainers.
> 
> My request for becoming maintainer of it has also yielded nothing, despite being present in the [CODEOWNERS file](https://github.com/pixelfed/pixelfed/blob/dev/CODEOWNERS) since my original PR was merged in

I merged your PRs, lets chat!
