### ISSUE TITLE
[Bug] Unfollowing Hashtags from Relationships List is not working

### ISSUE THREAD

**Issue by weinbrenner** [pixelfed/pixelfed#5008]
(related to #4907)

Unfollowing a hashtag from the view in settings: e.g.: https://pixelfed.social/settings/relationships/home?mode=hashtags&page=1 has a strange effect:

The hashtag seems to be unfollowed in the list and also when clicking somewhere on this hashtag, BUT all posts with this hashtag still appear in the timeline. Looks like there are two positions in the database where followed hashtags are stored!?

(If unfollowing from a hashtag page (e.g. https://pixelfed.social/i/web/hashtag/[SOMEHASHTAGNAME]) everthing seems to work fine.

**Comment by Offerel** [comment]
This seems to be not fixed. With curl --request GET --url https://pixel.tchncs.de/api/v1/followed_tags --header 'authorization: Bearer MYTOKEN', i get:

[
  {
    "name": "darktable",
    "url": "https://pixel.tchncs.de/i/web/hashtag/darktable",
    "history": [],
    "following": true
  }
]

When i now do: curl --request POST --url https://pixel.tchncs.de/api/v1/tags/darktable/unfollow --header 'authorization: Bearer MYTOKEN', i get:

{
  "name": "DarkTable",
  "url": "https://pixel.tchncs.de/i/web/hashtag/darktable-1",
  "history": [],
  "following": false
}

reloading curl --request GET --url https://pixel.tchncs.de/api/v1/followed_tags --header 'authorization: Bearer MYTOKEN', gives me again

[
  {
    "name": "darktable",
    "url": "https://pixel.tchncs.de/i/web/hashtag/darktable",
    "history": [],
    "following": true
  }
]

Since im only a standard user, i have no idea, how to remove the hashtag. The mentioned instance is on "version": "3.5.3 (compatible; Pixelfed 0.12.7)"
