### ISSUE TITLE
Page not shown on iPhone in lock-down mode

### ISSUE THREAD

**Issue by xsuchy** [pixelfed/pixelfed#5017]
When browsing with iPhone in lock-down mode, the page renders empty. See screenshot.

![432469148_783709636522268_4974165037995657223_n](https://github.com/pixelfed/pixelfed/assets/85769/75ae2f65-5cf7-4b24-b0a2-13ce2b6ffef3)

This was reported when browsing self-hosted instance: pixelfed.cz/dnesnaukrajine

I myself does not have iPhone, but several people confirmed this.

**Comment by Wild1145** [comment]
This I believe is by design, iOS will not execute or render content on "Complex" websites (Which usually means anything that is executing client side code I suspect). iOS does have the option through clicking the button in the middle of the bottom bar to disable lockdown mode for a given website, I would suggest that is what individuals should do (Or alternatively just turn off lockdown mode given Apple don't recommend the vast majority of people even use it)
