### ISSUE TITLE
Nextcloud Federation API for adding remotely shared photos and folders

### ISSUE THREAD

**Issue by sunjam** [pixelfed/pixelfed#531]
* [Nextcloud Gallery App](https://github.com/nextcloud/gallery)
* [Here is info on federated cloud api that Nextcloud currently uses for easily sharing and adding remote webdav folders and files between Nextcloud, Owncloud and Pydio](https://www.schiessle.org/articles/2016/07/04/history-and-future-of-cloud-federation/).  It would be awesome to be able to add these folders & photos to Pixelfed!  I know Nextcloud supports ActivityPub to some extent in order to federate with other Nextcloud instances.
* [Here is their current plan for expanding federation into an Open Cloud Mesh API](https://help.nextcloud.com/t/nextcloud-pushes-forward-open-cloud-mesh-api-with-proposal-for-1-0-release/33172).  Actual development is tracked [here on Github](https://github.com/GEANT/OCM-API/pull/37)

**Comment by sunjam** [comment]
Perhaps @jancborchardt can advise

**Comment by jancborchardt** [comment]
Thank you so much for starting this @sunjam! :) I’m not the best person to help here as I’m mostly interaction designer. cc @schiessle @rullzer @juliushaertl for deeper Nextcloud API and federation knowledge.

**Comment by jancborchardt** [comment]
@dansup if there’s anything missing or specifics that you need, you are welcome to open an issue in our server repository too! https://github.com/nextcloud/server/issues/

**Comment by Tauta2** [comment]
_Sent from my Pixel 3 XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Tauta2** [comment]
_Sent from my Pixel 3 XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jancborchardt** [comment]
Just FYI, with Nextcloud 15 we introduced Nextcloud Social 0.1 alpha, which uses the ActivityPub protocol. :slightly_smiling_face: 
https://github.com/nextcloud/social#nextcloud-social

**Comment by sunjam** [comment]
Fwiw, I still think this would be an amazing feature!  Best of luck with Pixelfed.

**Comment by trwnh** [comment]
As currently filed, the issue is unactionable. What form would integration with Nextcloud take? Does Nextcloud even create AS2 representations of the files themselves, e.g. Create Image, Create Video? Or does it use an extension of WebDav to handle file sharing between Nextcloud instances? In any case, Pixelfed currently only deals with Create Note, attachment[Image,Video]. So conceptually, it would seem cool to attach remote media (#1326 for a similar request with YouTube) but perhaps neither Pixelfed nor Nextcloud are at a stage where such an integration will work. Pixelfed is still hardcoded to assume local storage, so even S3 support (#1139) is still not strictly possible until that underlying work is complete. We may revisit this in the future, however, once there is a more concrete proposal.

**Comment by jancborchardt** [comment]
cc @daita @violoncelloch @juliushaertl of Nextcloud Social here. :)
