### ISSUE TITLE
[Feature] Different privacy settings for picture and comment

### ISSUE THREAD

**Issue by 7usr7local** [pixelfed/pixelfed#538]
Allowing to show nice pictures to the world, but keeping additional info to selected people (e.g. followers) would allow to gain appreciation by the whole world, but keeping sensitvie information (as the place, the event, the time the picture was taken) more private.

**Comment by pqhf5kd** [comment]
This is a great idea

**Comment by trwnh** [comment]
This might not be strictly possible in ActivityPub semantics. The object has metadata attached, but fetching objects is currently all-or-nothing. This is because very object is addressed to a certain audience. In order to make certain things have a different privacy/audience than the post, those things would have to be their own objects, and they would require their own audience. Otherwise, you would have some fetching fail silently due to an auth failure.
