### ISSUE TITLE
Timeline paging only includes 3 posts in Safari

### ISSUE THREAD

**Issue by jumoru** [pixelfed/pixelfed#661]
When using Pixelfed with Safari on iOS & macOS the timelines end after a few posts. It seems as if this happens at the point where other browsers usually load and show older pictures after a few seconds.

(iOS 12.1.2 and macOS 10.14.2 with Safari 12.0.2 (extensions disabled))

**Comment by trwnh** [comment]
Can confirm that each timeline page only contains 3 entries for some reason. It's 6 in Firefox.

**Comment by dansup** [comment]
Timelines now load 4 posts at a time. Infinite scroll may cause some browsers to load the next page which is why you would see 3 or 6 posts or now 4 or 8 on first load. This is not a bug.

https://github.com/pixelfed/pixelfed/blob/5a94ed7ba79c7a9a4b5beaf976032ed507a4221f/resources/assets/js/components/Timeline.vue#L443-L448
