### ISSUE TITLE
Everything should be editable after publication

### ISSUE THREAD

**Issue by thomas-kuntz** [pixelfed/pixelfed#823]
I opened #822 about the fact that we can't edit the post caption after publishing, but that's also true about the post license, the visibility and the ability to add additional media to the post.

I think all of this should be editable after post publication. 🙂

**Comment by dansup** [comment]
@thomaskuntzz Post captions will never be editable due to how other implementations handle ActivityPub. Adding additional media to the post will not federate, neither will updating post licence or visibility.

**Comment by trwnh** [comment]
post caption should be editable, regardless of what other implementations do. we can still send an `Update` activity and only compatible implementations will process it. it absolutely will federate, there's just no guarantee that other implementations will do anything with activities they don't understand. in fact, pixelfed has the potential to be one of the first activitypub implementations that supports `Update` activities for content, aside from maybe friendica

**Comment by thomas-kuntz** [comment]
> @thomaskuntzz Post captions will never be editable due to how other implementations handle ActivityPub. Adding additional media to the post will not federate, neither will updating post licence or visibility.

Oh, that's surprising... Is it ActivityPub itself that prevents this kind of thing to happen or just some other federated software that won't be able to handle that?

**Comment by dansup** [comment]
> post caption should be editable, regardless of what other implementations do. we can still send an `Update` activity and only compatible implementations will process it. it absolutely will federate, there's just no guarantee that other implementations will do anything with activities they don't understand.

The problem with that is the potential for abuse. Here is an example:

- Bob posts "dogs are the best animal"
- Alice boosts the post
- Bob edits the post to something offensive and Alice followers are unaware of the original post, thinking Alice boosted an offensive post.

**Comment by thomas-kuntz** [comment]
Right... Maybe that could be gotten around by notifying Alice that Bob's post has been edited, so that she can check and see what to do, but that would add a layer of complexification.

**Comment by dansup** [comment]
> Right... Maybe that could be gotten around by notifying Alice that Bob's post has been edited, so that she can check and see what to do, but that would add a layer of complexification.

A potential solution is to let users delay creation like Gmail Undo. This would allow them to edit the post in a short window (ie: 30-60 seconds) before the post is published and delivered via AP. This would be trivial to support since I planned post drafts/scheduling and the migrations were added months ago.

**Comment by thomas-kuntz** [comment]
Yes but it would be a very partial solution.

What if I post stuff and a few days/weeks/months later I want to edit my captions to change my tone, add info or whatever (that's the kind of cases I was thinking about)? I would have to delete the post and publish it again. That's not a good solution.

The 'undo' option would not help with that: if I realize that I made a typo in a post that I just published, I can just as well delete it and re-publish it right away.

**Comment by trwnh** [comment]
i'm not sure "potential for abuse" is any different when every single web page has been editable at any time. i can link to a page and say "hey check out this cool page", and then several months down the road, the domain expires and some hateful content is put up there by the new owner. i'm not sure i'm comfortable with the assumption that social media content should be immutable and unchanging forever, because retractions happen and people can change, for whatever reason.

if the concern is about boosting something that changes, then there are other solutions to that problem:
- the internal representation of what alice `Announce`s can be stored, i.e. keep a revision log and point to the old version, then insert a notice that a newer version of that post exists.
- more extreme answer: discard all interactions on posts that have been updated
- community answer: bob is suspended for posting hateful stuff and the boost disappears from alice's profile since it is no longer valid

**Comment by spaceottercode** [comment]
@thomaskuntzz I have found ActivityPub to be like email in many ways (but not 100%). 

@trwnh the qualifier extreme made me smile ('more extreme answer') only because this is pretty much what Mastodon does with the redraft option: delete and post with the added convenience of not having to upload media anew. (note I'm not advocating for this. just sayin').

@ all 
some places, like Wikipedia, tackle this dishonesty with revisions like @trwnh mentioned. I'm not 100% sure how this could be implemented without burdening developers or users. One _partial_ solution could be:

if comments are shown chronologically then we can leverage that and add separators (perhaps a line with the date of revision, or whatnot, centered). If comments are not sorted chronologically then this is a no-go. This partial solution does not address: what about replies.

Not addressed: how revisions are implemented, how users can view revisions in a simple fashion, if at all,...

sorry for the incomplete brainstorm.

**Comment by ReitzBytes** [comment]
@dansup Is this still out of the question? Post editability is a huge value to users imo. When I'm introducing new users to pixelfed I can instantly see the excitement die when I tell them they can't edit their previous posts.

**Comment by trwnh** [comment]
https://github.com/pixelfed/pixelfed/issues/1528#issuecomment-513476259

>Deleting and reposting is only a temporary workaround -- I do think we should plan on supporting editing captions. This has been previously discussed in #823 FWIW, but some more thought needs to be given to exactly how editing would work if implemented. If we plan to track diffs or old versions of Objects, then it would require a significant refactoring. If we simply add an "edited" indicator, it would not be so significant.
>
>IMO the only real issues with editing posts are that boosts/likes might be perceived to only reference the old Object and not the updated version. With likes, it's not such a big deal -- likes can be hidden or ignored or whatever. But boosts are more fundamentally complicated because you are effectively drawing attention to something that is outside of your control -- you are letting people embed arbitrary content on your pages. The only way around this is to either cache a static copy at the time of the boost, like archive.org or Tumblr, or to not support boosts at all.

**Comment by JeffAlyanak** [comment]
Technical details aside—I'll leave that discussion to those with more intimate knowledge of the ActivityPub protocol—the License should probably not be editabe.

It just makes it a nightmare for people who might use a work and cite the license. You'd need to restrict the edits to licenses that are more permissive, which can't be done given the current firm that the license field takes.

**Comment by lapineige** [comment]
I don't see (or don't understand ?) any reference to NSFW status (or CW content) in this issue.
Is it possible to edit this, with the current ActivityPub ?

It would be really handy to be able to add a NSFW status (hide the media) after publishing, for 2 user case: one forgot to activate it (and has to redo the whole publication), or didn't realise that it could impact some users (and may be warmed by someone), but is reluctant to delete&redo the publication, as well as loosing all comments, shares and likes.

**Comment by gbraad** [comment]
> It just makes it a nightmare for people who might use a work and cite the license.

IANAL, but as the owner of a work I am always able to relicense them, regardless this being published online or in print.

**Comment by JeffAlyanak** [comment]
> > It just makes it a nightmare for people who might use a work and cite the license.
> 
> IANAL, but as the owner of a work I am always able to relicense them, regardless this being published online or in print.

I don't believe that is the case with most open licenses. You might be able to license the same work to someone else under a more restrictive license but you cannot rescind an open license retroactively.

If Alice found my work while it was GPL and used it in some other work then me changing the license to be more restrictive will not affect her. I have already licensed the work to Alice and have not reserved any right to alter that agreement in future.

Of course, if Bob comes along after I've changed the license then he would be bound by the new, more restrictive license. However, the nature of the original license means that Alice can license the work to Bob as she has been granted those rights.

...

As I said, it just makes it a nightmare.

**Comment by gbraad** [comment]
> rescind an open license retroactively. 

Definetely a nightmare, as it depends on the license.

Just in general, an edit option is not ideal... especially in a federated setup as no-one can guarantee the other end will update. The NSFW usecase showed the 'forgotten' option, but what if I revoke the 'sensitive nature'? If you want to edit, why not just create a new post? People seemed to have accepted this with Identi.ca years before (as Twitter). However, I think Peertube allows edits, but only on the textual content and not the uploaded media ... right? Pretty much as YouTube (and the part that people hate for not being able to re-upload a video. You can if not reached 20.000 views or so, which Cody's Lab recently experienced as not being helpful. It seems there is no perfect solution except being opinionated.

**Comment by jklawiter** [comment]
>     * Bob posts "dogs are the best animal"
> 
>     * Alice boosts the post
> 
>     * Bob edits the post to something offensive and Alice followers are unaware of the original post, thinking Alice boosted an offensive post.
* than Alice is unfollowing Bob leaving him in his kiddy sandbox, and normal ppl have still ability to add hashtag or correct mistake/error in caption.

**Comment by lapineige** [comment]
And a "edited" label could be present somewhere to prove that it was changed.

**Comment by dansup** [comment]
You can now edit posts across the webUI, mobile apps and 3rd party clients! 🥳
