### ISSUE TITLE
Own posts don't show up in personal timeline

### ISSUE THREAD

**Issue by arjenpdevries** [pixelfed/pixelfed#85]
Compare my profile page:
https://pixelfed.social/arjen

and my timeline:
https://pixelfed.social/timeline

Great project btw.

**Comment by ghost** [comment]
This might be best renamed to "people's own posts don't show up in their personal timeline" if that's the main point? That didn't make sense to me either (especially because looking at the public timeline, you _can_ see your own posts. just not in your personal timeline.)

(please do let me know if i'm misunderstanding the issue)

**Comment by arjenpdevries** [comment]
True. 

See also https://mastodon.social/@pixelfed/100128357253774335
