### ISSUE TITLE
Unlisted posts are not listed on profile page

### ISSUE THREAD

**Issue by Seestern** [pixelfed/pixelfed#939]
I have an account on Pixelfed and posted 10 pictures - 2 as "Pubic" and 8 as "Unlisted (hidden from public timelines)".

When i call the site _pixelfed.de/username_ - **and i am not logged in** - the 2 public pictures are visible but the 8 unlisted are not.

When i call an unlisted picture with the URL _pixelfed.de/p/username/12345_ the picture is visible - **again, i am not logged in**.

I think, unlisted pictures should be allways visible.

**Comment by trwnh** [comment]
Hmm, this is more a question of what "unlisted" means. It currently means "not public", and therefore, "visible to anyone with the link". Consider an unlisted video on YouTube, which does not show up in a channel's feed. This makes sense.

What may be conflicting here is that other software like Mastodon has different expectations for what "unlisted" means -- in those case, the statuses and their links are visible on the profile pages, they are simply hidden from local/federated/hashtag timelines if the software uses the same logic as Mastodon. There is no technical difference between the two, and it is entirely a matter of interpretation. Ideally, there would be a clearer signal for whether a user is opting into public timelines, because unlisting means something different in many other softwares that are not Mastodon.
