### ISSUE TITLE
Favorites/like, boosts/share, and comments are not federating

### ISSUE THREAD

**Issue by amal-fi-haq** [pixelfed/pixelfed#942]
**Actual behavior**
1. PixelFed post (public) federates to followers outside PixelFed (in this case, Masto)
2. Followed PixelFed shows up in Home Timeline (in this case, Masto)
3. Masto sourced favorites, boosts, and comments are visible within Masto only and are NOT federated back to PixelFed post as likes, shares, and comments.
4. PixelFed sourced likes, shares, and comments are NOT federated back to Masto and thus are not visible.

**Expected behavior**
3/4.  Favorites/like, boosts/share, and comments are seen by both, inside PixelFed as well as outside (in the case, Masto)

**Ultimate Desire:**
- Via Masto: To boost my federated PixelFed posts. I will then no longer have to x-post on Masto for people to see my work. 

**Additional Info**
Mastodon 2.7.3
PixelFed 0.8.0rc1

@dansup, we discussed (follower-only) the matter a bit here:
https://toot.jeena.net/@jeena/101649599404705942

**Comment by trwnh** [comment]
You can track the progress of ActivityPub implementation in the pinned issue #5. To my current knowledge, the following are working (at least on whatever pixelfed.social deploys):

- Making a post sends an outgoing status visible in Masto (your 1st point)
- Following a Pixelfed user from Masto generally works (your 2nd point), but with one bug right now being #866
- Incoming likes/unlikes from Masto are added to your posts, and incoming replies from Masto are received as comments (your 3rd point)
- Commenting on a post sends an outgoing reply visible in Masto (your 4th point), there just isn't a visible mention embedded in the content for Masto. The addressing is still correct even if not visible.

So I think this is fixed in master, if not in 0.8.0rc1? @dansup should be able to confirm if this is correct.

**Comment by trwnh** [comment]
Sample Pixelfed post and comment in Mastodon:
![image](https://user-images.githubusercontent.com/10606431/53703757-2a667280-3ddb-11e9-8c63-c4cc75676b66.png)

Sample following in Mastodon: 
![image](https://user-images.githubusercontent.com/10606431/53703767-49650480-3ddb-11e9-882d-7724f853b73b.png)

**Comment by amal-fi-haq** [comment]
Both your samples are within my experience. It looks like comments from PixelFed are federating over to Masto. 

4. I need to amend point 4 by saying, "comments federate to Masto, but likes and shares do not." Additionally, deleting the comment on PixelFed does NOT delete it on Masto. 🤷‍♂️ 

3. Based on your sample following of dansup from Masto, can you use your Masto account to comment on that photo? I would like to know if your comment properly propagates over to PixelFed.  Further more, what of favorites and boosts? Do they show on his pixelfed?

Thanks for pointing me to ActivityPub Jobs #5. Looks like a lot some of what I am mentioning is a work in progress still. I need to look at that list more carefully later. 

I'm a bit ignorant with most of this and wish to be helpful. I want to avoid creating any new or duplicate  issues when there is no need. Thanks for your patience.  I love this project and what you all are doing.

**Comment by trwnh** [comment]
I guess this issue can be closed as a duplicate, then -- it's ok though, if you have any questions you can ask them and we can redirect you to where you should look :) I see you already found #737 as the tracker issue for Deletes specifically, as well.

To answer your specific questions:

4. Liking an incoming comment does not federate out yet, yeah. There's no way to reshare a comment yet.
5. I can comment on a Pixelfed post using my Masto account, but *only* if I reply to the top-level post in the Masto thread (the one that corresponds to the actual post). This is due to the lack of a thread resolver right now.

**Comment by amal-fi-haq** [comment]
@trwnh  Regarding point 5, I am still not able to reproduce the same behavior as you, even at the top level. I thought that perhaps this was due to my posting/commenting as "followers-only" on Masto, but I tried a public comment as well and still no 🎲🎲.

🤷‍♂️ 

![whatsapp image 2019-03-04 at 9 32 28 am](https://user-images.githubusercontent.com/48140605/53757149-263c6280-3e78-11e9-9085-427fa2f711e9.jpg)
![whatsapp image 2019-03-04 at 9 32 29 am](https://user-images.githubusercontent.com/48140605/53757151-28062600-3e78-11e9-8f30-1a7e1cf4bb7d.jpg)
![whatsapp image 2019-03-04 at 9 32 29 am 1](https://user-images.githubusercontent.com/48140605/53757156-2b011680-3e78-11e9-88b6-4402d4d36638.jpg)

**Comment by Whaxion** [comment]
I've made some investigations.
The masto comment as been catch by my instance, it's visible on the admin Statuses list. So, apparently, this comment isn't linked to the post.
